export const orario = `class,monday_1,monday_2,monday_3,monday_4,monday_5,monday_6,monday_7,monday_8,tuesday_1,tuesday_2,tuesday_3,tuesday_4,tuesday_5,tuesday_6,wednesday_1,wednesday_2,wednesday_3,wednesday_4,wednesday_5,wednesday_6,thursday_1,thurdsay_2,thurdsay_3,thurdsay_4,thurdsay_5,thurdsay_6,friday_1,friday_2,friday_3,friday_4,friday_5,friday_6
1 AC,"TIC
PUGLIESE
Info44","FRA
PRETTO","SC.INTEGR
.
DE SANTIS",LETT MARCHIOR O,"MATE
COMI","TPSC
CASONATO","ING
LACAVA",GEO CRESTANE LLO,"DIR E ECO
BIANCO","ING
LACAVA","SMS
LAGHETTO F
Palestra-1",,LETT MARCHIOR O,"MATE
COMI","TPSC
CASONATO VILLAREAL E","TPSC
CASONATO VILLAREAL E","TIC
DAMIANO PUGLIESE
Info44","FRA
PRETTO","MATE
COMI","DIR E ECO
BIANCO","ING
LACAVA","SC.INTEGR
. DE SANTIS TOSCANO","FRA
PRETTO","TPSC
CASONATO",IRC TAGLIAPIE TRA,STO MARCHIOR O,"LETT
MARCHIORO",,"FRA
PRETTO","MATE
COMI","TPSC
CASONATO VILLAREAL E","TPSC
CASONATO VILLAREAL E"
1 AM,"DIR E ECO
CUCCO","SC.INTEGR
.
PARISI","LETT
MANTESE",,GEO CRESTANE LLO,"ING
SCARSELLI","TIC
PUGLIESE",MATE CANNIZZA RO,MATE CANNIZZA RO,"SC.INTEGR.
PARISI,TOSCANO
Lab Fisica",,"LTE
CARERI
Off Meccanica",,,"LETT
MANTESE","TIC
DAMIANO PUGLIESE
InfoMulti",MATE CANNIZZA RO,"LTE
CARERI
Off Meccanica",,,MATE CANNIZZA RO,"DIR E ECO
CUCCO","IRC
TRABUCCO","ING
SCARSELLI","LETT
MANTESE","STO
MANTESE","SMS
ANTONIAZZI
Palestrona",,TTPG ADAMI BELLOTTI,TTPG ADAMI BELLOTTI,"ING
SCARSELLI","SC.INTEGR
. PARISI TOSCANO
Lab Fisica"
1 ART,"SC.INTEGR
.
PARISI","TIC
CUTRINO,P IANEGOND A",GEO CRESTANE LLO,"LTE,AMORELLI,Off Meccanica",,,"MATE
FILIACI","ING
SCARSELLI",LETT SPADAROT TO,STO SPADAROT TO,"MATE
FILIACI","SC.INTEGR
.
PARISI,TOS CANO","SMS
ZATTRA
Palestrona",,"TTPG ADAMI,DE MARIA","TTPG ADAMI,DE MARIA","DIR E ECO
CUCCO","ING
SCARSELLI","LETT
SPADAROTTO",,"ING
SCARSELLI","MATE
FILIACI",IRC TAGLIAPIE TRA,TIC PIANEGON DA,"SC.INTEGR.,PARISI,TOS CANO
Lab Fisica",,"MATE
FILIACI",LETT SPADAROT TO,"DIR E ECO
CUCCO","LTE,AMORELLI,Off Meccanica",,
,"LTE,BUSIN
Off Meccanica",,,"TIC
PIANEGON DA
Info44","SC.INTEGR.,PERRI,SAP ORITO
Lab Fisica",,"MATE
FILIACI","ING
SCARSELLI",LETT SPADAROT TO,STO SPADAROT TO,"MATE
FILIACI","TDP NOTARIELL O,PERIN","SMS
ZATTRA
Palestrona",,"LTE
BUSIN
Off Meccanica","SC.INTEGR
.
PERRI","DIR E ECO
CUCCO","ING
SCARSELLI","LETT
SPADAROTTO",,"ING
SCARSELLI","MATE
FILIACI",IRC TAGLIAPIE TRA,"LTE,BUSIN,Off Meccanica",,,"MATE
FILIACI",LETT SPADAROT TO,"DIR E ECO
CUCCO","TIC
CUTRINO,P IANEGOND A","TDP
NOTARIELLO,PERIN",
1 ARTM,"SC.INTEGR
.
PARISI","TIC
CUTRINO PIANEGON DA",,"LTE
AMORELLI
Off Meccanica",,,,,,,,"SC.INTEGR
. PARISI TOSCANO
Lab Fisica",,,TTPG ADAMI DE MARIA,TTPG ADAMI DE MARIA,,,,,,,,TIC PIANEGON DA,"SC.INTEGR.
PARISI,TOSCANO
Lab Fisica",,,,,"LTE
AMORELLI
Off Meccanica",,
1 ARTy,"LTE
BUSIN
Off Meccanica",,,"TIC
PIANEGON DA
Info44","SC.INTEGR.
PERRI,SAPORITO
Lab Fisica",,,,,,,TDP NOTARIELL O PERIN,,,"LTE
BUSIN
Off Meccanica","SC.INTEGR
.
PERRI",,,,,,,,"LTE
BUSIN
Off Meccanica",,,,,,"TIC
CUTRINO PIANEGON DA","TDP
NOTARIELLO,PERIN",
1 AS,"SMS
ZATTRA
Palestrona",,"MATE
FILIACI",GEO CRESTANE LLO,"MET OPER
PELLEGRIN",,"LETT
SPADAROTTO",,"TIC
CUTRINO PIANEGON DA","MATE
FILIACI","ING
BRIAN E","SC.INTEGR
.
DE SANTIS",SUS COPPOLA PELLEGRIN,,"FRA
PUTIN","MET OPER
PELLEGRIN",,"SUS
COPPOLA","IRC
RIGHELE","DIR E ECO
MARCHI","MATE
FILIACI",STO SPADAROT TO,LETT SPADAROT TO,"ING
BRIAN E","FRA
PUTIN","TIC
CUTRINO PIANEGON DA",LETT SPADAROT TO,"ING
BRIAN E","MATE
FILIACI","SC.INTEGR. DE SANTIS TOSCANO
Lab Fisica",,"DIR E ECO
MARCHI"
1 BC,"LETT
FILOSOFO","STO
FILOSOFO","FRA
PRETTO",TPSC MARANGO N,"MATE
VABLÈ",GEO CRESTANE LLO,"SC.INTEGR
. DE SANTIS SAPORITO","TIC
PUGLIESE","LETT
FILOSOFO",,"FRA
PRETTO","ING
DE TOMI","TPSC
DAMIANO MARANGO N","TPSC
DAMIANO MARANGO N","LETT
FILOSOFO","MATE
VABLÈ","FRA
PRETTO","DIR E ECO
BIANCO",TPSC MARANGO N,"TIC
DAMIANO PUGLIESE
Info44","SC.INTEGR
.
DE SANTIS","DIR E ECO
BIANCO","MATE
VABLÈ","ING
DE TOMI","TPSC DAMIANO MARANGON
Info44",,IRC TAGLIAPIE TRA,"MATE
VABLÈ","ING
DE TOMI","FRA
PRETTO","SMS
LAGHETTO F
Palestra-1",
1 BS,GEO CRESTANE LLO,FRA STOCCHER O,"TIC
CUTRINO PIANEGON DA","MET OPER
PELLEGRIN","SMS
SARTORI
Palestrona",,"LETT
FILOSOFO",,"MET OPER
PELLEGRIN","SC.INTEGR
.
DE SANTIS","MATE
VABLÈ","LETT
FILOSOFO","ING
DE TOMI","SUS
MARTINI","MATE
VABLÈ","IRC
RIGHELE","DIR E ECO
MARCHI","SUS
MARTINI MISTRORI GO","SC.INTEGR. DE SANTIS TOSCANO
Lab Fisica",,"STO
FILOSOFO","ING
DE TOMI","MET OPER
PELLEGRIN",,"TIC
CUTRINO PIANEGON DA","MATE
VABLÈ","ING
DE TOMI","LETT
FILOSOFO","MATE
VABLÈ",FRA STOCCHER O,"DIR E ECO
MARCHI","SUS
MARTINI MISTRORI GO"
2 AC,"TPSC
GECCHELIN","TPSC
GECCHELIN","ING
BRIAN E","FRA
PUTIN",LETT SPADAROT TO,"TIC
DAMIANO PUGLIESE
InfoComm",MATE CANNIZZA RO,"SC.INTEGR
. DE SANTIS SAPORITO","FRA
PUTIN","ING
BRIAN E","SMS
ZATTRA
Palestrona",,STO SPADAROT TO,MATE CANNIZZA RO,"TIC
PUGLIESE","FRA
PUTIN","SC.INTEGR
.
DE SANTIS","TPSC DAMIANO GECCHELIN
InfoCommerciale",,DIR E ECO EBALGINEL LI,STO SPADAROT TO,"ING
BRIAN E",DIR E ECO EBALGINEL LI,MATE CANNIZZA RO,"LETT
SPADAROTTO",,MATE CANNIZZA RO,"IRC
TRABUCCO",LETT SPADAROT TO,"TPSC DAMIANO GECCHELIN
InfoCommerciale",,"FRA
PUTIN"
2 AM,"MATE
COMI","DIR E ECO
CUCCO","SC.INTEGR.
PARISI,SAPORITO
Lab Fisica",,"ING
SCARSELLI","LETT
BORGO","LTE
CAZZOLA
Elettronica ,InfoMultim edia Off Elettrica-2",,"SC.INTEGR
.
PARISI","TIC
DAMIANO PIANEGON DA","MATE
COMI","LETT
BORGO",,"ING
SCARSELLI","ING
SCARSELLI","MATE
COMI","LETT
BORGO","STO
BORGO","LTE
CAZZOLA
Elettronica Off","TTPG
mecc4 PETRONE
Info45","LTE
CAZZOLA
Elettronica ,Off Elettrica-2",,,"IRC
TRABUCCO","DIR E ECO
CUCCO","MATE
COMI","TTPG
mecc4 PETRONE
Info45","TTPG
mecc4 PETRONE
Info45","SMS
ANTONIAZZI
Palestrona",,TIC PIANEGON DA,"STO
BORGO"
2 AS,"SC.INTEGR. DE SANTIS TOSCANO
Lab Fisica",,"STO
FILOSOFO","MATE
FILIACI","TIC
DAMIANO PIANEGON DA","FRA
PUTIN","SUS
MARTINI","DIR E ECO
MARCHI","MATE
FILIACI","SUS
MARTINI,PELLEGRIN",,"TIC
DAMIANO PIANEGON DA","LETT
FILOSOFO",,"SC.INTEGR
.
DE SANTIS","LETT
FILOSOFO","ING
SCARSELLI",IRC TAGLIAPIE TRA,"MET OPER
PELLEGRIN",,"SUS
MARTINI","LETT
FILOSOFO","ING
SCARSELLI","MATE
FILIACI","MET OPER
PELLEGRIN","FRA
PUTIN","DIR E ECO
MARCHI","MATE
FILIACI","ING
SCARSELLI","STO
FILOSOFO","SMS
ZATTRA
Palestrona",
2 AYm,STO MARCHIOR O,LETT MARCHIOR O,"ING
PUPPI","LTE
CARERI
Off Macchine Utensili",,,"SC.INTEGR
.
PERRI","MATE
FILIACI","SMS
SARTORI
Palestrona",,"ING
PUPPI","MATE
FILIACI","TDP
CURASÌ,me
cc5
InfoMulti","SC.INTEGR
. PERRI TOSCANO
Lab Fisica","LTE
CARERI
Off Macchine","DIR E ECO
BIANCO","TDP
CURASÌ,me
cc5
InfoMulti",TIC PIANEGON DA,IRC TAGLIAPIE TRA,LETT MARCHIOR O,"LETT
MARCHIORO",,"ING
PUPPI","DIR E ECO
BIANCO","MATE
FILIACI","TDP
CURASÌ,me
cc5
InfoMulti","LTE
CARERI
Off Macchine Utensili",,"SC.INTEGR
. PERRI TOSCANO
Lab Fisica",STO MARCHIOR O,"MATE
FILIACI","TIC
DAMIANO PIANEGON DA"
2 BM,"LETT
LETIZIA","STO
LETIZIA","DIR E ECO
CUCCO","ING
BAÙ","SC.INTEGR
.
PARISI","MATE
COMI","TTPG
CARERI,mecc5
Info45",,"ING
BAÙ","MATE
COMI","STO
LETIZIA","LTE
CICCAZZO
Off Elettrica-2",,,"SMS
ANTONIAZZI
Palestra-1",,"MATE
COMI","ING
BAÙ","TIC
CUTRINO PIANEGON DA","LETT
LETIZIA","LETT
LETIZIA",,"TIC
PIANEGON DA
Info44","TTPG
CARERI
mecc5
Info45","MATE
COMI","DIR E ECO
CUCCO","SC.INTEGR.
PARISI,TOSCANO
Lab Fisica",,IRC TAGLIAPIE TRA,"LTE
CICCAZZO
Off Elettrica-2","LTE
CICCAZZO
Info45 ,Off Elettrica-2",
2 BS,"TIC
DAMIANO PIANEGON DA","LETT
BADOLATO",,"SUS
CONTE,PIGNATELLI",,"ING
LACAVA","DIR E ECO
MARCHI","MATE
VABLÈ","MET OPER
CONTE",,SUS PIGNATELL I,IRC TAGLIAPIE TRA,"ING
LACAVA","MATE
VABLÈ","FRA
PRETTO","SC.INTEGR
.
DE SANTIS","MATE
VABLÈ","DIR E ECO
MARCHI","LETT
BADOLATO",,"MET OPER
CONTE","TIC
DAMIANO PIANEGON DA","SC.INTEGR. DE SANTIS TOSCANO
Lab Fisica",,"FRA
PRETTO",SUS PIGNATELL I,"SMS
SARTORI
Palestra-1",,"ING
LACAVA","MATE
VABLÈ","STO
BADOLATO",
3 AC,"FRA
PRETTO",DIR E ECO EBALGINEL LI,"MATE
DE PRETTO","TPSC
CUTRINO MARCHETT I",TPSC MARCHETT I,"STO
NAPOLI",IRC TAGLIAPIE TRA,"ING
DE TOMI","LETT
NAPOLI","STO
NAPOLI","ING
DE TOMI","FRA
PRETTO",TPSC MARCHETT I,DIR E ECO EBALGINEL LI,ING MICRO DE TOMI,"COM
MARTINI",DIR E ECO EBALGINEL LI,TPSC MARCHETT I,"SMS
SARTORI
Palestra-0",,"LETT
NAPOLI",,"TPSC CUTRINO MARCHETTI
InfoCommerciale",,"MATE
DE PRETTO",DIR E ECO EBALGINEL LI,"MATE
DE PRETTO","TPSC
MARCHETTI",,"LETT
NAPOLI","COM
MARTINI","FRA
PRETTO"
3 AM,"TTIMD
GAZZIN",MATE SCORTEGA GNA,"LETT
DE MAGGIO","STO
DE MAGGIO","ING
BAÙ","TEEA
BELLOTTI IOVANE
Elettronica","TMA DE
RIGO PETRONE
Off","TMA DE
RIGO PETRONE
Off","LTE
AMORELLI
Off Macchine Utensili",,MATE SCORTEGA GNA,"ING
BAÙ","LETT
DE MAGGIO","STO
DE MAGGIO","TEEA
BELLOTTI IOVANE
Elettronica","LTE
AMORELLI
Off Macchine Utensili",,"TMA
DE RIGO","SMS
ANTONIAZZI
Palestra-1",,"TTIMD
CARERI,GAZZIN
Misure",,,"TEEA
BELLOTTI IOVANE
Elettronica",MATE SCORTEGA GNA,"TMA
DE RIGO","IRC
TRABUCCO","LETT
DE MAGGIO",,"TMA DE
RIGO PETRONE
Info45","TEEA
BELLOTTI",ING MICRO BAÙ
3 ART,"TTIMD
DALLE MOLLE,SAGGIN
Auto/Saldatura",,"TTIMD
SAGGIN","TEEA
BELLOTTI,I OVANE
Elettronica","LETT
MARCHIORO",,"TMA
DALLE MOLLE,SAGGIN
Off Macchine Utensili",,"LTE,NOTARIELLO
Auto/Saldatura",,"TMA
DALLE MOLLE,SA GGIN","ING
LACAVA",MATE CANNIZZA RO,STO MARCHIOR O,MATE CANNIZZA RO,"ING
LACAVA","LTE
NOTARIELL O
Auto/Sald","TEEA
BELLOTTI","TMA
SAGGIN","TTIMD
DALLE MOLLE,SA GGIN","SMS
SARTORI
Palestra-1",,LETT MARCHIOR O,STO MARCHIOR O,MATE CANNIZZA RO,ING MICRO LACAVA,"TEEA,BELLOTTI,IOVANE
Elettronica",,"LTE,NOTARIELLO
Auto/Saldatura",,"IRC
RIGHELE",LETT MARCHIOR O
,"LTE,BUONO,Off Macchine Utensili",,,"TMPP
SAGGIN",,,"PP,CURASÌ,PERIN,CNC",,"PP,CURASÌ,PERIN
InfoMultimedia",,"PP
CURASÌ,PE RIN
CNC ,Info",,,,,,"TMPP
ADAMI,SA GGIN
Misure","TMPP
ADAMI,SA GGIN
InfoMulti","LTE,BUONO
Off Macchine Utensili",,,,,,,,"TMPP,ADAMI,SAGGIN
Misure",,"LTE
BUONO
Off Macchine","PP,PERIN",,
3 ARTMt,"TTIMD
DALLE MOLLE SAGGIN
Auto/Saldatura",,"TTIMD
SAGGIN","TEEA
BELLOTTI IOVANE
Elettronica",,,"TMA
DALLE MOLLE,SAGGIN
Off Macchine Utensili",,"LTE
NOTARIELLO
Auto/Saldatura",,"TMA
DALLE MOLLE SAGGIN",,,,,,"LTE
NOTARIELL O
Auto/Sald","TEEA
BELLOTTI","TMA
SAGGIN","TTIMD
DALLE MOLLE SAGGIN",,,,,,,"TEEA
BELLOTTI,IOVANE
Elettronica",,"LTE
NOTARIELLO
Auto/Saldatura",,,
3 ARTy,"LTE
BUONO
Off Macchine Utensili",,,"TMPP
SAGGIN",,,"PP CURASÌ,PERIN CNC",,"PP
CURASÌ,PERIN
InfoMultimedia",,"PP CURASÌ
PERIN CNC
InfoMulti media",,,,,,"TMPP
ADAMI SAGGIN
Misure","TMPP
ADAMI SAGGIN
InfoMulti","LTE
BUONO
Off Macchine Utensili",,,,,,,,"TMPP
ADAMI,SAGGIN
Misure",,"LTE
BUONO
Off Macchine","PP
PERIN",,
3 AS,"DETA
BIANCO","ING
BRIAN E","MATE
COMI","PSICO
COPPOLA","IGIENE
RONCAGLIA",,"MET OPER
PELLEGRIN",,"LETT
APOLLONI","PSICO
COPPOLA","FRA
PUTIN","ING
BRIAN E","MATE
COMI","DETA
BIANCO","IRC
RIGHELE","STO
APOLLONI","IGIENE
RONCAGLIA",,ING MICRO BRIAN E,"MATE
COMI","SMS
ZATTRA
Palestra-0",,"LETT
APOLLONI","PSICO
COPPOLA",,"STO
APOLLONI","FRA
PUTIN","PSICO
COPPOLA","DETA
BIANCO","LETT
APOLLONI",,"MET OPER
PELLEGRIN"
3 BS,"LETT
DE MAGGIO",,"DETA
BIANCO","ING
PUPPI","PSICO
COPPOLA","MATE
VABLÈ","IGIENE
CAU",,"LETT
DE MAGGIO","MATE
VABLÈ","DETA
BIANCO","PSICO
COPPOLA","FRA
PRETTO","ING
PUPPI","PSICO
COPPOLA",,"SMS
ZATTRA
Palestra-0",,"MET OPER
MISTRORIGO",,"IGIENE
CAU",,"PSICO
COPPOLA","FRA
PRETTO","STO
DE MAGGIO","LETT
DE MAGGIO","MATE
VABLÈ","DETA
BIANCO",ING MICRO PUPPI,"STO
DE MAGGIO","MET
OPER MISTRORI GO","IRC
RIGHELE"
3BMa,"ING
BAÙ",TEEA PIETRIBIA SI,"SMS
ANTONIAZZI
Palestra-1",,"TTIMD
GAZZIN",MATE DE PRETTO,STO BERTOLOT TI,LETT BERTOLOT TI,"TMA PETRONE ZANIN
Info45","TTIMD GAZZIN URSO
Elettronic","LETT
BERTOLOTTI",,"LTE
CAZZOLA
Off Elettrica-","LTE
CAZZOLA
InfoMulti media Off",STO BERTOLOT TI,MATE DE PRETTO,"TEEA PIETRIBIA SI URSO
Lab122","TEEA PIETRIBIA SI URSO
Off","TTIMD GAZZIN,U RSO
Off","IRC
RIGHELE","ING
BAÙ",MATE DE PRETTO,LETT BERTOLOT TI,"TMA
PETRONE,ZANIN
Off Macchine Utensili",,"TMA
ZANIN","LTE
CAZZOLA
Off Elettrica-1",,TEEA PIETRIBIA SI,"TEEA PIETRIBIA SI URSO
Elettronic",ING MICRO BAÙ,"TTIMD GAZZIN URSO
Elettronic"
4 AC,DIR E ECO EBALGINE LLI,"COM
MARTINI","SMS
ZATTRA
Palestrona",,"STO
NAPOLI","FRA
PRETTO","TPSC
CASONATO",,IRC TAGLIAPIE TRA,"TPSC CASONATO CUTRINO
InfoCommerciale",,MATE DE PRETTO,DIR E ECO EBALGINE LLI,"ING
DE TOMI","COM
MARTINI","FRA
PRETTO",TPSC CASONAT O,TPSC CASONAT O,DIR E ECO EBALGINE LLI,"LETT
NAPOLI","ING
DE TOMI",DIR E ECO EBALGINE LLI,"LETT
NAPOLI",,TPSC CASONAT O,MATE DE PRETTO,"STO
NAPOLI","LETT
NAPOLI",MATE DE PRETTO,TPSC CASONAT O,"FRA
PRETTO",ING MICRO DE TOMI
4 ART1,MATE DE PRETTO,"ING
PUPPI","STO
LO BRUTTO","TTIMD
MANIA","TEEA BELLOTTI,I OVANE
Elettronic","TMA
DE RIGO","LTE,NOTARIELLO
Auto/Saldatura",,"SMS
ANTONIAZZI
Palestra-1",,"TEEA
BELLOTTI","TMA DALLE MOLLE,DE
RIGO","LETT
LO BRUTTO",MATE DE PRETTO,"TTIMD DALLE MOLLE,M
ANIA","TEEA BELLOTTI,I OVANE
Elettronic","TEEA BELLOTTI,I OVANE
Elettronic","STO
LO BRUTTO","LETT
LO BRUTTO",MATE DE PRETTO,"ING
PUPPI","TTIMD
DALLE MOLLE,MANIA
Auto/Saldatura",,,"LTE,NOTARIELLO,Auto/Saldatura",,ING MICRO PUPPI,"LETT
LO BRUTTO",,IRC TRABUCC O,"TMA
DALLE MOLLE,DE RIGO
Off Macchine Utensili",
,,,,"LTE,BUONO,CNC",,,"TMPP,DE MARIA,URSO
Info44 ,Misure",,,,PP ZARANTO NELLO,"PP
CURASÌ,ZA RANTONE LLO",,,"LTE,BUONO,CNC",,,,,,,"PP
CURASÌ,ZARANTONEL LO
CNC ,InfoMultimedia",,"TMPP
DE MARIA","TMPP,DE MARIA,URSO
Elettronica ,Info45",,,,,,"PP
CURASÌ,ZARANTONEL LO
Auto/Saldatura",
4 ART1Mt,,,,"TTIMD
MANIA","TEEA
BELLOTTI IOVANE
Elettronic","TMA
DE RIGO","LTE
NOTARIELLO
Auto/Saldatura",,,,"TEEA
BELLOTTI","TMA
DALLE MOLLE DE RIGO",,,"TTIMD
DALLE MOLLE MANIA","TEEA
BELLOTTI IOVANE
Elettronic","TEEA
BELLOTTI IOVANE
Elettronic",,,,,"TTIMD
DALLE MOLLE MANIA
Auto/Saldatura",,,"LTE
NOTARIELLO
Auto/Saldatura",,,,,,"TMA
DALLE MOLLE,DE RIGO
Off Macchine Utensili",
4 ART1y,,,,LTE BUONO CNC,,,"TMPP
DE MARIA,URSO
Info44 ,Misure",,,,PP ZARANTO NELLO,"PP CURASÌ ZARANTO
NELLO",,,LTE BUONO CNC,,,,,,,"PP
CURASÌ ZARANTONELLO
CNC ,InfoMultimedia",,"TMPP
DE MARIA","TMPP
DE MARIA,URSO
Elettronica ,Info45",,,,,,"PP
CURASÌ ZARANTONELLO
Auto/Saldatura",
4 ART2,MATE SCORTEG AGNA,"TEEA,GAZZIN,IOVANE
Elettronica ,Info45",,"TTIMD
ADAMI,PI ETRIBIASI
Info45","LTE,URSO
Info44 ,Off Elettrica-1",,"SMS
ANTONIAZZI
Palestrona",,"ING
BRIAN E",MATE SCORTEG AGNA,"STO
LO BRUTTO","LETT
LO BRUTTO","TMA,DE RIGO,PETRONE
Off Macchine Utensili",,"TMA
DE RIGO,PET RONE","ING
BRIAN E","LETT
LO BRUTTO","TEEA
GAZZIN,IO VANE
Elettronic","TTIMD
ADAMI,PI ETRIBIASI
Misure","TTIMD
ADAMI,PI ETRIBIASI
Misure",IRC TRABUCC O,MATE SCORTEG AGNA,"LTE
URSO
Off Elettrica-","TEEA
GAZZIN","TEEA
GAZZIN","LETT
LO BRUTTO",TTIMD PIETRIBIA SI,"TMA
DE RIGO","LTE
URSO
Off Elettrica-",ING MICRO BRIAN E,"STO
LO BRUTTO","LETT
LO BRUTTO"
,,"PP
CURASÌ,PE RIN
CNC ,Info","PP
CURASÌ,PERIN
Auto/Saldatura ,Info Multimedia",,"TMPP,ADAMI,DE
MARIA
InfoMultimedia ,Misu re",,,,,,,,"TMPP,ADAMI,DE MARIA
Elettronica ,Info45",,"PP,PERIN",,,"LTE,BUSIN,CNC",,,,,"TMPP
DE MARIA","PP,CURASÌ,PERIN
CNC ,InfoMultimedia",,,"LTE,BUSIN,CNC",,,,,
4 ART2Ma,,"TEEA
GAZZIN,IOVANE
Elettronica ,Info45",,"TTIMD ADAMI PIETRIBIA
SI","LTE
URSO
Info44 ,Off Elettrica-1",,,,,,,,"TMA
DE RIGO,PETRONE
Off Macchine Utensili",,"TMA DE RIGO PETRONE
Info45",,,"TEEA GAZZIN IOVANE
Elettronic","TTIMD ADAMI PIETRIBIA
SI","TTIMD ADAMI PIETRIBIA
SI",,,"LTE
URSO
Off Elettrica-","TEEA
GAZZIN","TEEA
GAZZIN",,TTIMD PIETRIBIA SI,"TMA
DE RIGO","LTE
URSO
Off Elettrica-",,,
4 ART2y,,"PP CURASÌ
PERIN
CNC
InfoMulti","PP
CURASÌ,PERIN
Auto/Saldatura ,Info Multimedia",,"TMPP
ADAMI,DE MARIA
InfoMultimedia ,Misu re",,,,,,,,"TMPP
ADAMI,DE MARIA
Elettronica ,Info45",,"PP
PERIN",,,LTE BUSIN CNC,,,,,"TMPP
DE MARIA","PP
CURASÌ,PERIN
CNC ,InfoMultimedia",,,LTE BUSIN CNC,,,,,
4 AS,"ING
PUPPI",PSICO PIGNATEL LI,IRC TAGLIAPIE TRA,"DETA
GRASSO E","FRA
PUTIN",MATE CANNIZZA RO,"LETT
BORGO",,PSICO PIGNATEL LI,MATE CANNIZZA RO,"LETT
BORGO","FRA
PUTIN","ING
PUPPI","DETA
GRASSO E","IGIENE
RONCAGLIA",,"DETA
GRASSO E",PSICO PIGNATEL LI,"LETT
BORGO","STO
BORGO","PSICO
PIGNATELLI",,"SMS
SARTORI
Palestra-0",,"MET OPER
CONTE",,"DETA
GRASSO E",ING MICRO PUPPI,MATE CANNIZZA RO,"STO
BORGO","IGIENE
RONCAGLIA",
4 BC,TPSC MARANG ON,TPSC MARANG ON,DIR E ECO EBALGINE LLI,"LETT
LETIZIA","STO
LETIZIA","ING
DE TOMI","MATE
MARSETTI",FRA STOCCHER O,"LETT
LETIZIA",,IRC TAGLIAPIE TRA,TPSC MARANG ON,"MATE
MARSETTI",COM PIGNATEL LI,"SMS
ZATTRA
Palestra-0",,FRA STOCCHER O,DIR E ECO EBALGINE LLI,"LETT
LETIZIA",TPSC MARANG ON,DIR E ECO EBALGINE LLI,"MATE
MARSETTI","TPSC
MARANGON",,COM PIGNATEL LI,"ING
DE TOMI","TPSC CUTRINO MARANGON
InfoCommerciale",,FRA STOCCHER O,ING MICRO DE TOMI,"STO
LETIZIA",DIR E ECO EBALGINE LLI
4 BS,"MET OPER
CONTE",,"PSICO
MARTINI",,"DETA
GRASSO E","MATE
MARSETTI","FRA
PUTIN","ING
LACAVA","ING
LACAVA","STO
DE MAGGIO","LETT
DE MAGGIO","PSICO
MARTINI","IGIENE
RONCAGLIA",,IRC TAGLIAPIE TRA,"MATE
MARSETTI","PSICO
MARTINI","DETA
GRASSO E","LETT
DE MAGGIO",,"DETA
GRASSO E","PSICO
MARTINI","IGIENE
RONCAGLIA",,"SMS
SARTORI
Palestra-0",,ING MICRO LACAVA,"FRA
PUTIN","DETA
GRASSO E","MATE
MARSETTI","STO
DE MAGGIO","LETT
DE MAGGIO"
5 AC,IRC TAGLIAPIE TRA,MATE DE PRETTO,"LETT
NAPOLI",,DIR E ECO EBALGINE LLI,TPSC GECCHELI N,FRA STOCCHER O,"COM
MARTINI","COM
MARTINI",DIR E ECO EBALGINE LLI,"STO
NAPOLI","ING
SCARSELLI","TPSC CUTRINO GECCHELIN
InfoCommerciale",,TPSC GECCHELI N,TPSC GECCHELI N,MATE DE PRETTO,"LETT
NAPOLI","LETT
NAPOLI",FRA STOCCHER O,"TPSC
GECCHELIN",,MATE DE PRETTO,DIR E ECO EBALGINE LLI,"STO
NAPOLI","ING
SCARSELLI",ING MICRO SCARSELLI,FRA STOCCHER O,"SMS
LAGHETTO F
Palestra-1",,DIR E ECO EBALGINE LLI,TPSC GECCHELI N
5 AM,"TEEA
IOVANE PIETRIBIA SI","TTIMD
AMORELLI,DE RIGO
Misure",,MATE DE PRETTO,"STO
MANTESE","LETT
MANTESE","SMS
SARTORI
Palestra-1",,"TTIMD
DE RIGO","TMA
ZANIN","TMA
PETRONE,ZANIN
Off Macchine Utensili",,MATE DE PRETTO,"ING
LACAVA",MATE DE PRETTO,"LETT
MANTESE",,"LTE
AMORELLI
Off Macchine","TTIMD
AMORELLI DE RIGO
Info45","ING
LACAVA","LTE
AMORELLI
Off Macchine Utensili",,"TMA
PETRONE ZANIN
Info45",ING MICRO LACAVA,"TTIMD
DE RIGO",IRC TAGLIAPIE TRA,"LTE
AMORELLI
Auto/Saldatura",,"LETT
MANTESE","STO
MANTESE","TEEA
IOVANE,PIETRIBIASI
Misure",
5 AS,"ING
BRIAN E","DETA
GRASSO E","PSICO
COPPOLA","MATE
COMI","STO
APOLLONI","LETT
APOLLONI","IGIENE
RONCAGLIA",,"PSICO
COPPOLA","LETT
APOLLONI",,"MATE
COMI","ING
BRIAN E","FRA
PUTIN","STO
APOLLONI","DETA
GRASSO E",IRC TAGLIAPIE TRA,"MATE
COMI","PSICO
COPPOLA",,"IGIENE
RONCAGLIA",,"DETA
GRASSO E","LETT
APOLLONI","SMS
ZATTRA
Palestra-1",,"PSICO
COPPOLA","DETA
GRASSO E",ING MICRO BRIAN E,"FRA
PUTIN","MET OPER
CONTE",
5 AYm,"PP
DE MARIA NOTARIEL LO CNC","PP
DE MARIA","ING
SCARSELLI",MATE CANNIZZA RO,MATE CANNIZZA RO,"TMPP
SAGGIN","STO
LO BRUTTO","LETT
LO BRUTTO","STO
LO BRUTTO","LETT
LO BRUTTO","ING
SCARSELLI","TMPP SAGGIN URSO
InfoCom",LTE BUONO CNC,,"TMPP SAGGIN URSO
InfoCom",ING MICRO SCARSELLI,"SMS
LAGHETTO F
Palestra-1",,"PP
DE MARIA NOTARIELLO
InfoMultimedia",,"TMPP
SAGGIN,URSO
InfoCommerciale ,Off Elettrica-1",,MATE CANNIZZA RO,"LETT
LO BRUTTO",,LTE BUONO CNC,"PP
DE MARIA NOTARIELLO
InfoMultimedia",,IRC TRABUCC O,,LTE BUONO CNC,
5 BC,COM PIGNATEL LI,TPSC MARCHET TI,TPSC MARCHET TI,FRA STOCCHER O,LETT BERTOLOT TI,STO BERTOLOT TI,"MATE
VABLÈ",IRC TAGLIAPIE TRA,"MATE
VABLÈ","DIR E ECO
BIANCO","TPSC
MARCHETTI",,"SMS
LAGHETTO F
Palestra-1",,"DIR E ECO
BIANCO","TPSC CUTRINO MARCHETTI
InfoCommerciale",,"ING
BRIAN E",FRA STOCCHER O,COM PIGNATEL LI,"ING
BRIAN E",TPSC MARCHET TI,"DIR E ECO
BIANCO","MATE
VABLÈ",STO BERTOLOT TI,LETT BERTOLOT TI,"DIR E ECO
BIANCO","LETT
BERTOLOTTI",,TPSC MARCHET TI,ING MICRO BRIAN E,FRA STOCCHER O
5 BMa,"SMS
SARTORI
Palestra-1",,"LTE
CAZZOLA
Off Elettrica-","TTIMD
CAZZOLA GAZZIN
Misure","ING
LACAVA","LETT
LETIZIA","TEEA
ADAMI,BE LLOTTI
Off","MATE
MARSETTI","MATE
MARSETTI","LTE
CAZZOLA
Info44 ,Off Elettrica-1",,"TTIMD
CAZZOLA GAZZIN
Elettronic","TEEA
BELLOTTI","STO
LETIZIA","LTE
CAZZOLA
Off Elettrica-1",,"TMA
PERIN,PETRONE
Info45",,"ING
LACAVA","TTIMD
GAZZIN","MATE
MARSETTI",ING MICRO LACAVA,"LETT
LETIZIA",,"TEEA
ADAMI BELLOTTI
InfoCom","TEEA
ADAMI,BE LLOTTI
Off","LETT
LETIZIA","STO
LETIZIA","TMA
PERIN PETRONE
Info45","TTIMD
CAZZOLA GAZZIN
Misure","TTIMD
GAZZIN",IRC TAGLIAPIE TRA
5 BS,"DETA
GRASSO E",IRC TAGLIAPIE TRA,MATE SCORTEG AGNA,LETT BERTOLOT TI,"SMS
ANTONIAZZI
Palestra-1",,"ING
DE TOMI","FRA
PUTIN",MATE SCORTEG AGNA,PSICO PIGNATEL LI,"IGIENE
RONCAGLIA",,"DETA
GRASSO E",STO BERTOLOT TI,"DETA
GRASSO E",PSICO PIGNATEL LI,LETT BERTOLOT TI,"ING
DE TOMI","MET OPER
CONTE",,"LETT
BERTOLOTTI",,PSICO PIGNATEL LI,"DETA
GRASSO E",ING MICRO DE TOMI,MATE SCORTEG AGNA,"PSICO
PIGNATELLI",,"IGIENE
RONCAGLIA",,"FRA
PUTIN",STO BERTOLOT TI
5 CMt,"TTIMD
MANIA","TTIMD
MANIA","ING
BAÙ","MATE
MARSETTI","LTE
BUSIN
Auto/Saldatura",,"STO
APOLLONI","LETT
APOLLONI","TMA
DALLE MOLLE ZARANTONELLO CNC",,"TEEA
GAZZIN IOVANE
Misure","LTE
BUSIN
Auto/Saldatura",,,"MATE
MARSETTI","LTE
BUSIN
Auto/Sald atura","STO
APOLLONI","TTIMD
DALLE MOLLE MANIA
Auto/Saldatura",,"ING
BAÙ","TTIMD
DALLE MOLLE MANIA",ING MICRO BAÙ,"SMS
ANTONIAZZI
Palestra-1",,"LETT
APOLLONI","TEEA
GAZZIN IOVANE
InfoCom","LETT
APOLLONI",,"TEEA
GAZZIN IOVANE
Misure","TMA
DALLE MOLLE ZARANTO",IRC TAGLIAPIE TRA,"MATE
MARSETTI"
`;
