export const orario = `
class,wednesday_1,wednesday_2,wednesday_3,wednesday_4,thursday_1,thursday_2,thursday_3,thursday_4,friday_1,friday_2,friday_3,friday_4
1AC,"TIC
DAMIANO,PUGLIESE
InfoCom","SC.INT.
LUPPINO
Lab Fisica","TPSC
DAMIANO,GECCHELIN","ING
LACAVA","TPSC
GECCHELIN","MATE
COMI","SMS
FOSCARINI
Palestra","LETT
BOSSARD","DIR/ECO
EBALGINELLI","MATE
COMI","TPSC
GECCHELIN","LETT
BOSSARD"
1AM,"ING
IGNAZZI","TTPG
CAZZOLA,ZANROSSO","IRC
TAGLIAPIETRA","STO
LO BRUTTO","DIR/ECO
LONGOBARDI","LETT
LO BRUTTO","ING
IGNAZZI","LTE
CARERI
Off Mec","LTE
CARERI
Off Mec","LETT
LO BRUTTO","SC.INT.
SURIANO,TOSCANO","TIC
PIANEGONDA,SPAMPINATO
Info44"
1AS,"MATE
CANNIZZARO","LETT
PAVAN","TIC
PIANEGONDA
Info44","SUS
PELLEGRIN,PIGNATELLI","MET OP
PELLEGRIN","MATE
CANNIZZARO","SMS
SARTORI","ING
FACCI","LETT
PAVAN","DIR/ECO
MARCHI","MET OP
PELLEGRIN","FRA
STOCCHERO"
1AYm,"LETT
APOLLONI M","SMS
ZATTRA
Palestra","SC.INT.
LUPPINO,RIGONI
Lab Fisica","ING
IGNAZZI","MATE
SBANOTTO","DIR/ECO
LONGOBARDI","LTE
BUONO
Off Mec","TIC
PUGLIESE","LETT
APOLLONI M","ING
IGNAZZI","MATE
SBANOTTO","SMS
ZATTRA"
1BM,"TTPG
CARERI,PIETRIBIASI","SMS
ANTONIAZZI","SC.INT.
SURIANO,TOSCANO","MATE
VABLÈ","TIC
PUGLIESE
Info44","LETT
CARAMIA","TTPG
CARERI,PIETRIBIASI","DIR/ECO
BIANCO","SC.INT.
SURIANO,TOSCANO
Lab Fisica","TIC
PUGLIESE,SPAMPINATO
Info44","MATE
VABLÈ","LETT
CARAMIA"
1BS,"FRA
STOCCHERO","SUS
PIGNATELLI","DIR/ECO
GRASSO E","MET OP
CONTE","SMS
SARTORI","ING
FACCI","LETT
CARAMIA","SC.INT.
LAZZARI,TOSCANO
Lab Fisica","LETT
CARAMIA","FRA
STOCCHERO","MATE
COMI","SUS
CONTE,PIGNATELLI"
1CS,"DIR/ECO
MARCHI","TIC
CUTRINO,PUGLIESE
Info44","ING
DE TOMI","LETT
CARAMIA","LETT
CARAMIA","TIC
CUTRINO,PUGLIESE
Info44","SUS
CONTE,MINOZZO","SMS
FOSCARINI","ING
DE TOMI","LETT
CARAMIA","DIR/ECO
MARCHI","IRC
TAGLIAPIETRA"
2 AC,"TPSC
CASONATO","MATE
COMI","LETT
MARCHIORO","SC.INT.
LUPPINO
Lab Fisica","ING
LACAVA","SMS
FOSCARINI
Palestra","TIC
DAMIANO,PUGLIESE
InfoMulti","TPSC
CASONATO,DAMIANO
InfoMulti","ING
LACAVA","TPSC
CASONATO","DIR/ECO
BIANCO","MATE
COMI"
2 AM,"SC.INT.
SURIANO","DIR/ECO
LONGOBARDI","SMS
ANTONIAZZI","LETT
MANTESE","IRC
TRABUCCO","TTPG
IOVANE,PIETRIBIASI
InfoMulti","TIC
PIANEGONDA","LETT
MANTESE","TIC
PIANEGONDA,SPAMPINATO
Info45","ING
TABACCHINO","MATE
CANNIZZARO","TTPG
IOVANE
InfoMulti"
2 ART,"TIC
PIANEGONDA
InfoMulti",,"DIR/ECO
LONGOBARDI","ING
TABACCHINO",,"SMS
ZATTRA","LETT
SPADAROTTO",,,"LETT
SPADAROTTO","IRC
TAGLIAPIETRA",
2 ARTM,,"TTPG
DE MARIA
Info45",,,"LTE
URSO
Off Elett2",,,"TTPG
DE MARIA
Info45","LTE
URSO
Off Elett2",,,"SC.INT.
SURIANO,TOSCANO
Lab Fisica"
2 ARTy,,"LTE
BUSIN
Off MacUtensili",,,"TDP
ZOVI
Info45",,,"LTE
BUSIN","LTE
BUSIN
Off MacUtensili",,,"SC.INT.
RIGONI"
2 AS,"SC.INT.
TOSCANO
Lab Fisica","ING
BRIAN E","LETT
SPADAROTTO","TIC
CUTRINO,PIANEGONDA
InfoMulti","LETT
SPADAROTTO","FRA
PUTIN","SUS
COPPOLA,PELLEGRIN","MET OP
PELLEGRIN","STO
SPADAROTTO","SUS
COPPOLA","IRC
RIGHELE","DIR/ECO
MARCHI"
2 BC,"TPSC
MARANGON","FRA
FABBI","LETT
PAVAN","TIC
DAMIANO,PUGLIESE
InfoCom","DIR/ECO
BIANCO","ING
DE TOMI","MATE
VABLÈ","LETT
PAVAN","TPSC
DAMIANO,MARANGON
InfoCom","SMS
FOSCARINI
Palestra","SC.INT.
LUPPINO
Lab Fisica","FRA
FABBI"
2 BS,"LETT
BOSSARD","FRA
STOCCHERO","MATE
VABLÈ","SMS
SARTORI","MET OP
CONTE","LETT
BOSSARD","SC.INT.
TOSCANO
Lab Fisica","MATE
VABLÈ","DIR/ECO
MARCHI","IRC
RIGHELE","MET OP
CONTE","SUS
MARTINI"
3 AC,"SMS
ZATTRA
Palestra","FRA
PUTIN","DIR/ECO
EBALGINELLI","LETT
SPADAROTTO","MATE
CANNIZZARO","IRC
TRABUCCO","TPSC
GECCHELIN","COM
COPPOLA","ING
BRIAN E","TPSC
DAMIANO,GECCHELIN
InfoCom","LETT
SPADAROTTO","FRA
PUTIN"
3 ART1,"MATE
SBANOTTO","LETT
MARCHIORO",,,,"IRC
TAGLIAPIETRA","LETT
MARCHIORO","MATE
SBANOTTO","LETT
MARCHIORO","ING
FACCI",,"MATE
SBANOTTO"
3 ART1Mt,,,"TTIMD
MANIA
Auto/Sald","TEEA
CAZZOLA,ZANROSSO
Elettronica,Misure","TEEA
CAZZOLA
Elettronica,Misure",,,,,,"TEEA
CAZZOLA",
3 ART1y,,,"PP
PERIN
InfoMulti","ING MICRO
FACCI","TMPP
DE MARIA",,,,,,"PP
PERIN",
3 ART2,"LETT
BORGO",,,"SMS
ANTONIAZZI
Palestra",,,"MATE
COMI",,"ING
TABACCHINO","IRC
TAGLIAPIETRA",,"SMS
ANTONIAZZI
Palestra"
3ART2C,,"TIC
PIANEGONDA
InfoCom","TPSC
CUTRINO,MARCHETTI
InfoCom",,"TIC
PIANEGONDA
InfoCom","DIR/ECO
BIANCO",,"ING MICRO
TABACCHINO",,,"FRA
FABBI",
3ART2M,,"ING MICRO
IGNAZZI","TEEA
BELLOTTI,ESPOSITO
Off Elett2",,"LTE
CARERI
Off MacUtensili","TEEA
BELLOTTI",,"TMA
ACOCELLA
Off MacUtensili",,,"LTE
CARERI
Off MacUtensili",
3 AS,"MET OP
PELLEGRIN","IRC
TAGLIAPIETRA","PSY
MARTINI","DETA
GRASSO E","ING
TABACCHINO","LETT
BERTOLOTTI","MATE
SCORTEGAGNA","SMS
ZATTRA
Palestra","MATE
SCORTEGAGNA","IGIENE
RONCAGLIA","FRA
PUTIN","LETT
BERTOLOTTI"
3 BMa,"TMA
ZOVI
Off Mec","MATE
SBANOTTO","ING
TABACCHINO","LETT
LETIZIA","TEEA
ESPOSITO,GAZZIN
Off Elett1","LTE
CICCAZZO","IRC
TRABUCCO","TTIMD
CAZZOLA
Elettronica","TTIMD
PIETRIBIASI","LETT
LETIZIA","SMS
ANTONIAZZI
Palestra","TEEA
ESPOSITO,GAZZIN
Elettronica,Off Elett1"
3 BS,"ING
LACAVA","MATE
VABLÈ","PSY
PIGNATELLI","LETT
APOLLONI M","LETT
APOLLONI M","ING MICRO
LACAVA","PSY
PIGNATELLI","DETA
GRASSO E","SMS
SARTORI","MET OP
CONTE","DETA
GRASSO E","MATE
VABLÈ"
4 AC,"TPSC
MARCHETTI","DIR/ECO
EBALGINELLI","LETT
BOSSARD","MATE
DE PRETTO","ING
DE TOMI","COM
MARTINI","TPSC
CUTRINO,MARCHETTI
InfoCom","DIR/ECO
EBALGINELLI","LETT
BOSSARD","COM
MARTINI","FRA
STOCCHERO","DIR/ECO
EBALGINELLI"
4 AM,"TEEA
BELLOTTI","LTE
URSO
Off Elett1","TMA
ACOCELLA
Info45","LETT
PAVAN","SMS
ANTONIAZZI
Palestra","MATE
SCORTEGAGNA","ING
FACCI","TTIMD
CICCAZZO,GAZZIN
Misure","TMA
ACOCELLA","TTIMD
GAZZIN","IRC
TRABUCCO","STO
PAVAN"
4 ART,"LETT
MARCHIORO",,"ING
LACAVA",,"LETT
MARCHIORO",,,"MATE
CANNIZZARO",,"LETT
MARCHIORO",,
4 ARTMt,,"TTIMD
ZOVI
Auto/Sald",,"TEEA
BELLOTTI",,"TTIMD
ZOVI
Auto/Sald","TEEA
BELLOTTI,IOVANE
Misure",,"ING MICRO
IGNAZZI",,"TEEA
IOVANE
Elettronica,Misure","TTIMD
ZOVI
Auto/Sald"
4 ARTy,,"TMPP
ACOCELLA",,"LTE
BUONO
CNC",,"LTE
BUONO
CNC","PP
PERIN
Auto/Sald",,"PP
PERIN
InfoMulti",,"TMPP
ACOCELLA","LTE
BUONO
CNC"
4 AS,"FRA
PUTIN","MET OP
PELLEGRIN","IGIENE
RONCAGLIA","DETA
BIANCO","PSY
COPPOLA","LETT
APOLLONI M","DETA
BIANCO","MATE
COMI","IRC
RIGHELE","FRA
PUTIN","SMS
ZATTRA
Palestrona","LETT
APOLLONI M"
4 BMa,"SMS
ANTONIAZZI","ING
TABACCHINO","TTIMD
PIETRIBIASI,URSO
Elettronica","TEEA
GAZZIN","TTIMD
PIETRIBIASI","TEEA
ESPOSITO,GAZZIN
Elettronica,Off Elett1","TMA
ZOVI","LETT
BERTOLOTTI","LTE
CAZZOLA
Off Elett1","LETT
BERTOLOTTI","MATE
DE PRETTO","IRC
RIGHELE"
4 BS,"LETT
LETIZIA","PSY
COPPOLA","DETA
BIANCO","IGIENE
RONCAGLIA","ING
BRIAN E","MATE
VABLÈ","SMS
ZATTRA","LETT
LETIZIA","DETA
BIANCO","ING MICRO
BRIAN E","LETT
LETIZIA","IGIENE
RONCAGLIA"
5 AC,"DIR/ECO
EBALGINELLI","LETT
MANTESE","MATE
DE PRETTO","FRA
FABBI","DIR/ECO
EBALGINELLI","TPSC
CASONATO","LETT
MANTESE","COM
MARTINI","FRA
FABBI","SMS
ZATTRA","COM
MARTINI","TPSC
CASONATO,CUTRINO
InfoCom"
5 ART1,,"LETT
LO BRUTTO","STO
LO BRUTTO",,,,"LETT
LO BRUTTO","MATE
DE PRETTO",,,"LETT
LO BRUTTO","IRC
TRABUCCO"
5 ART1Mt,"TEEA
IOVANE,ZANROSSO
Elettronica,Misure",,,"TTIMD
MANIA
Auto/Sald","TTIMD
MANIA","TMA
ZARANTONELLO
Info45",,,"ING MICRO
FACCI","TMA
ZARANTONELLO
CNC",,
5 ART1y,"LTE
BUONO
CNC",,,"TMPP
DE MARIA","PP
ZARANTONELLO
InfoMulti","TMPP
DE MARIA
Misure",,,"PP
ZARANTONELLO
CNC","LTE
BUONO",,
5 ART2,"LETT
LO BRUTTO",,,,"MATE
SCORTEGAGNA",,,,"SMS
ANTONIAZZI
Palestrona",,,"LETT
LO BRUTTO"
5 ART2Ma,,"TEEA
GAZZIN,IOVANE
Off Elett2","TMA
ZOVI
Off MacUtensili","TTIMD
PIETRIBIASI",,"ING MICRO
BRIAN E","LTE
URSO
Off Elett2","TMA
ZOVI",,"TTIMD
IOVANE,PIETRIBIASI
Elettronica,Misure","LTE
URSO
Off Elett2",
5 ART2y,,"TMPP
ESPOSITO","LTE
BUSIN
CNC","PP
PERIN",,"ING MICRO
IGNAZZI","TMPP
DE MARIA,ESPOSITO
Info45","PP
PERIN",,"TMPP
DE MARIA","LTE
BUSIN
CNC",
5 AS,"DETA
GRASSO E","MET OP
CONTE","LETT
BORGO","IRC
TAGLIAPIETRA","PSY
PIGNATELLI","IGIENE
RONCAGLIA","MATE
CANNIZZARO","FRA
PUTIN","IGIENE
RONCAGLIA","SMS
SARTORI
Palestrona","STO
BORGO","ING
LACAVA"
5 BC,"COM
PIGNATELLI","LETT
LETIZIA","MATE
MARSETTI","DIR/ECO
EBALGINELLI","TPSC
MARANGON","LETT
LETIZIA","ING
DE TOMI","IRC
TAGLIAPIETRA","FRA
STOCCHERO","ING
DE TOMI","TPSC
CUTRINO,MARANGON
InfoCom","LETT
LETIZIA"
5 BS,"PSY
MARTINI","MATE
MARSETTI","LETT
BERTOLOTTI","STO
BERTOLOTTI","LETT
BERTOLOTTI","DETA
GRASSO E","PSY
MARTINI","IGIENE
RONCAGLIA","FRA
PUTIN","DETA
GRASSO E","ING
LACAVA","SMS
SARTORI
Palestrona"
`;
