export const orario = `
class,monday_1,monday_2,monday_3,monday_4,monday_5,tuesday_1,tuesday_2,tuesday_3,tuesday_4,tuesday_5,wednesday_1,wednesday_2,wednesday_3,wednesday_4,wednesday_5,thursday_1,thursday_2,thursday_3,thursday_4,thursday_5,friday_1,friday_2,friday_3,friday_4,friday_5
1AC,"TIC
PUGLIESE
InfoCom","TIC
PUGLIESE
InfoCom","SMS
FOSCARINI
Palestrona","SMS
FOSCARINI
Palestrona","MATE
COMI","TPSC
GECCHELIN","GEO
ZAMBERLAN","ING
LACAVA","DIR/ECO
EBALGINELLI","MATE
COMI","TPSC
GECCHELIN","TIC DAMIANO PUGLIESE
InfoCom","MATE
COMI","ING
LACAVA","LETT
BOSSARD","LETT
BOSSARD","LETT
BOSSARD","MATE
COMI","ING
LACAVA","DIR/ECO
EBALGINELLI","TPSC
DAMIANO,GECCHELIN
InfoCom","TPSC
DAMIANO,GECCHELIN
InfoCom","SC.INT.
LUPPINO","IRC
TAGLIAPIETRA","LETT
BOSSARD"
1AM,"SC.INT.
SURIANO","LETT
LO BRUTTO","STO
LO BRUTTO","ING
IGNAZZI","GEO
ZAMBERLAN","DIR/ECO
LONGOBARDI","SC.INT.
SURIANO
Lab Fisica","TIC
PIANEGONDA
Info44","LTE
CARERI
Off Mec","LTE
CARERI
Off Mec","ING
IGNAZZI","SC.INT. SURIANO TOSCANO
Lab Fisica","SC.INT.
SURIANO
Lab Fisica","DIR/ECO
LONGOBARDI","TTPG
CAZZOLA ZANROSSO","LETT
LO BRUTTO","LETT
LO BRUTTO","ING
IGNAZZI","LTE
CARERI
Off Mec","LTE
CARERI
Off Mec","IRC
TAGLIAPIETRA","LETT
LO BRUTTO","TIC PIANEGONDA SPAMPINATO
Info44","TTPG
CAZZOLA","TTPG
CAZZOLA"
1AS,"GEO
ZAMBERLAN","SUS
PIGNATELLI","MATE
CANNIZZARO","ING
FACCI","DIR/ECO
MARCHI","SMS
SARTORI
Palestra.","SMS
SARTORI
Palestra.","SC.INT.
TOSCANO
Lab Fisica","SC.INT.
TOSCANO
Lab Fisica","MATE
CANNIZZARO","LETT
PAVAN","LETT
PAVAN","ING
FACCI","FRA
STOCCHERO","MATE
CANNIZZARO","MET OP
PELLEGRIN","STO
PAVAN","MATE
CANNIZZARO","SUS
PELLEGRIN,PIGNATELLI","SUS
PELLEGRIN,PIGNATELLI","TIC PIANEGONDA SPAMPINATO
Info44","ING
FACCI","FRA
STOCCHERO","MET OP
PELLEGRIN","MET OP
PELLEGRIN"
1AYm,"SC.INT.
LUPPINO,RIGONI
Lab Fisica","SC.INT.
LUPPINO,RIGONI
Lab Fisica","TIC CUTRINO PUGLIESE
Info45","LTE
BUONO","LTE
BUONO","MATE
SBANOTTO","ING
IGNAZZI","STO
APOLLONI","GEO
ZAMBERLAN","DIR/ECO
LONGOBARDI","SC.INT.
RIGONI","ING
IGNAZZI","LTE
BUONO
Off Mec","LTE
BUONO
Off Mec","DIR/ECO
LONGOBARDI","MATE
SBANOTTO","LETT
APOLLONI","SMS
ZATTRA
Palestra","SMS
ZATTRA
Palestra","ING
IGNAZZI","IRC
TRABUCCO","MATE
SBANOTTO","LTE
BUONO
Off Mec","LTE
BUONO
Off Mec","TIC
PUGLIESE
Info45"
1BM,"LTE
BUSIN
Off Mec","DIR/ECO
BIANCO","IRC
TAGLIAPIETRA","SC.INT. SURIANO TOSCANO
Lab Fisica","TIC PUGLIESE SPAMPINATO
Info44","LTE
BUSIN
Off Mec","LETT
CARAMIA","GEO
ZAMBERLAN","MATE
VABLÈ","SC.INT. SURIANO TOSCANO
Lab Fisica","SC.INT. SURIANO TOSCANO
Lab Fisica","MATE
VABLÈ","TTPG
CARERI PIETRIBIASI","TIC
PUGLIESE
Info44","MATE
VABLÈ","TTPG
CARERI PIETRIBIASI","LTE
BUSIN
Off Mec","LTE
BUSIN
Off Mec","MATE
VABLÈ","LETT
CARAMIA","LTE
BUSIN
Off Mec","LTE
BUSIN
Off Mec","LETT
CARAMIA","LETT
CARAMIA","SC.INT.
SURIANO"
1BS,"STO
CARAMIA","LETT
CARAMIA","FRA
STOCCHERO","MATE
COMI","MET OP
CONTE","GEO
ZAMBERLAN","SUS
CONTE,PIGNATELLI","SUS
CONTE,PIGNATELLI","MATE
COMI","ING
FACCI","SMS
SARTORI
Palestra.","SMS
SARTORI
Palestra.","DIR/ECO
GRASSO E","SC.INT. LAZZARI TOSCANO
Lab Fisica","MATE
COMI","MET OP
CONTE","ING
FACCI","LETT
CARAMIA","LETT
CARAMIA","SC.INT. LAZZARI TOSCANO
Lab Fisica","LETT
CARAMIA","MATE
COMI","IRC
TAGLIAPIETRA","FRA
STOCCHERO","TIC PIANEGONDA SPAMPINATO
Info44"
1CS,"SUS
CONTE","DIR/ECO
MARCHI","GEO
ZAMBERLAN","TIC
CUTRINO
Info44","SC.INT.
LUPPINO","SMS
FOSCARINI
Palestra","SMS
FOSCARINI
Palestra","ING
DE TOMI","LETT
CARAMIA","LETT
CARAMIA","LETT
CARAMIA","LETT
CARAMIA","TIC
PUGLIESE
Info44","IRC
TAGLIAPIETRA","ING
DE TOMI","STO
CARAMIA","LETT
CARAMIA","SUS
MINOZZO","SUS
MINOZZO","SUS
CONTE MINOZZO","ING
DE TOMI","DIR/ECO
MARCHI","SUS
CONTE","TIC CUTRINO PUGLIESE
Info44","SC.INT.
LUPPINO
Lab Fisica"
2 AC,"TPSC
CASONATO,DAMIANO
InfoMulti","TPSC
CASONATO,DAMIANO
InfoMulti","ING
LACAVA","SC.INT.
LUPPINO","SMS
FOSCARINI
Palestra","DIR/ECO
BIANCO","MATE
COMI","TPSC CASONATO DAMIANO
InfoMulti","SMS
FOSCARINI","ING
LACAVA","ING
LACAVA","MATE
COMI","LETT
MARCHIORO","LETT
MARCHIORO","TPSC CASONATO DAMIANO
InfoMulti","STO
MARCHIORO","LETT
MARCHIORO","TIC DAMIANO PUGLIESE
InfoMulti","TPSC
CASONATO","MATE
COMI","DIR/ECO
BIANCO","LETT
MARCHIORO","STO
MARCHIORO","TPSC
CASONATO","IRC
TAGLIAPIETRA"
2 AM,"ING
TABACCHINO","DIR/ECO
LONGOBARDI","STO
MANTESE","STO
MANTESE","LTE
CAZZOLA
Elettronica Off Elett1","LTE
CAZZOLA
Off Elett2","LTE
CAZZOLA
Off Elett2","MATE
CANNIZZARO","ING
TABACCHINO","LETT
MANTESE","DIR/ECO
LONGOBARDI","TTPG
PIETRIBIASI","MATE
CANNIZZARO","ING
TABACCHINO","SC.INT. SURIANO TOSCANO
Lab Fisica","MATE
CANNIZZARO","IRC
TRABUCCO","LTE
CAZZOLA
Elettronica,Off Elett2","LTE
CAZZOLA
Elettronica,Off Elett2","LETT
MANTESE","SC.INT.
SURIANO","TIC
PIANEGONDA
Info45","TTPG
PIETRIBIASI
InfoMulti","TTPG
PIETRIBIASI
InfoMulti","MATE
CANNIZZARO"
2 ART,"LETT
SPADAROTTO","LETT
SPADAROTTO","ING
TABACCHINO","DIR/ECO
LONGOBARDI","TIC
CUTRINO,PIANEGONDA
InfoMulti","SMS
ZATTRA
Palestrona","SMS
ZATTRA
Palestrona","SC.INT.,SURIANO","STO
SPADAROTTO","IRC
TAGLIAPIETRA","LETT
SPADAROTTO","DIR/ECO
LONGOBARDI","LTE,URSO
Off Elett2","LTE,URSO,Off Elett2","LTE,URSO,Off Elett2","STO
SPADAROTTO","LETT
SPADAROTTO","LTE,URSO","LTE,URSO","TIC
PIANEGONDA
InfoMulti","LTE,URSO,Off Elett2","LTE,URSO,Off Elett2","SC.INT.,SURIANO,TOSCANO
Lab Fisica","SC.INT.,SURIANO,TOSCANO
Lab Fisica","ING
TABACCHINO"
2 ART,"LETT
SPADAROTTO","LETT
SPADAROTTO","ING
TABACCHINO","DIR/ECO
LONGOBARDI","LTE
BUSIN
Off MacUtensili","SMS
ZATTRA
Palestrona","SMS
ZATTRA
Palestrona","TDP,ZOVI,Info45","STO
SPADAROTTO","IRC
TAGLIAPIETRA","LETT
SPADAROTTO","DIR/ECO
LONGOBARDI","TIC
CUTRINO,PIANEGONDA
InfoMulti","TDP,ZOVI,Info45","TDP,ZOVI,Info45","STO
SPADAROTTO","LETT
SPADAROTTO","TIC
PIANEGONDA","LTE,BUSIN,Off MacUtensili","LTE,BUSIN,Off MacUtensili","SC.INT.,LUPPINO,RIGONI
Lab Fisica","SC.INT.,LUPPINO,RIGONI
Lab Fisica","LTE,BUSIN,Off MacUtensili","LTE,BUSIN,Off MacUtensili","ING
TABACCHINO"
2 AS,"DIR/ECO
MARCHI","MET OP
PELLEGRIN","MET OP
PELLEGRIN","STO
SPADAROTTO","IRC
RIGHELE","MET OP
PELLEGRIN","LETT
SPADAROTTO","STO
SPADAROTTO","SUS
COPPOLA,PELLEGRIN","SUS
COPPOLA,PELLEGRIN","SMS
ZATTRA","TIC
CUTRINO PIANEGONDA
InfoMulti","SC.INT.
TOSCANO","LETT
SPADAROTTO","MET OP
PELLEGRIN","SUS
COPPOLA","TIC
CUTRINO PIANEGONDA
InfoMulti","SC.INT.
TOSCANO
Lab Fisica","SC.INT.
TOSCANO
Lab Fisica","SMS
ZATTRA","SUS
COPPOLA","SUS
COPPOLA","LETT
SPADAROTTO","DIR/ECO
MARCHI","LETT
SPADAROTTO"
2 BC,"IRC
TAGLIAPIETRA","SMS
FOSCARINI
Palestra.","SC.INT.
LUPPINO
Lab Fisica","FRA
FABBI","ING
DE TOMI","LETT
PAVAN","LETT
PAVAN","SMS
FOSCARINI
Palestra.","TPSC
MARANGON","DIR/ECO
BIANCO","TIC
PUGLIESE
InfoCom","FRA
FABBI","TPSC
DAMIANO,MARANGON
InfoCom","TPSC
DAMIANO,MARANGON
InfoCom","STO
PAVAN","LETT
PAVAN","ING
DE TOMI","STO
PAVAN","DIR/ECO
BIANCO","TIC DAMIANO PUGLIESE
InfoCom","LETT
PAVAN","ING
DE TOMI","TPSC
DAMIANO,MARANGON
InfoCom",,"FRA
FABBI"
2 BS,"IRC
RIGHELE","ING
DE TOMI","LETT
BOSSARD","STO
BOSSARD","MATE
VABLÈ","DIR/ECO
MARCHI","TIC
CUTRINO PIANEGONDA
InfoMulti","SMS
SARTORI
Palestrona","SMS
SARTORI
Palestrona","MATE
VABLÈ","SUS
MARTINI,PELLEGRIN","SUS
MARTINI,PELLEGRIN","LETT
BOSSARD","TIC
CUTRINO PIANEGONDA
InfoMulti","FRA
STOCCHERO","SC.INT.
TOSCANO
Lab Fisica","SC.INT.
TOSCANO
Lab Fisica","SUS
MARTINI","ING
DE TOMI","LETT
BOSSARD","MET OP
CONTE","MET OP
CONTE","DIR/ECO
MARCHI","MATE
VABLÈ","FRA
STOCCHERO"
3 AC,"MATE
CANNIZZARO","DIR/ECO
EBALGINELLI","COM
COPPOLA","TPSC
GECCHELIN","SMS
ZATTRA
Palestra.","LETT
SPADAROTTO","TPSC
GECCHELIN","TPSC
GECCHELIN","SMS
ZATTRA
Palestra.","DIR/ECO
EBALGINELLI","COM
COPPOLA","LETT
SPADAROTTO","STO
SPADAROTTO","DIR/ECO
EBALGINELLI","TPSC
GECCHELIN","TPSC
DAMIANO,GECCHELIN
InfoCom","TPSC
DAMIANO,GECCHELIN
InfoCom","DIR/ECO
EBALGINELLI","MATE
CANNIZZARO","STO
SPADAROTTO","LETT
SPADAROTTO","LETT
SPADAROTTO","IRC
TRABUCCO","MATE
CANNIZZARO","TPSC
GECCHELIN"
3 ART1,"SMS
SARTORI
Palestra","SMS
SARTORI
Palestra","TTIMD,MANIA
Auto/Sald","TEEA
ZANROSSO","LETT
MARCHIORO","LETT
MARCHIORO","MATE
SBANOTTO","MATE
SBANOTTO","ING
FACCI","TEEA,CAZZOLA","TEEA,ZANROSSO,Elettronica,Misure","TEEA,ZANROSSO,Elettronica,Misure","TTIMD,MANIA,Auto/Sald","TTIMD,MANIA,Auto/Sald","MATE
SBANOTTO","IRC
TAGLIAPIETRA","MATE
SBANOTTO","ING MICRO
FACCI","TTIMD,MANIA","LETT
MARCHIORO","TEEA,CAZZOLA","TEEA,CAZZOLA","ING
FACCI","TEEA
ZANROSSO","MATE
SBANOTTO"
3 ART1,"SMS
SARTORI
Palestra","SMS
SARTORI
Palestra","LTE,CARERI,Off MacUtensili","LTE,CARERI,Off MacUtensili","LETT
MARCHIORO","LETT
MARCHIORO","MATE
SBANOTTO","MATE
SBANOTTO","ING
FACCI","PP,PERIN
InfoMulti","LTE,CARERI,Off MacUtensili","LTE,CARERI,Off MacUtensili","PP,PERIN,CNC","PP,PERIN,CNC","MATE
SBANOTTO","IRC
TAGLIAPIETRA","MATE
SBANOTTO","LTE
CARERI
Off MacUtensili","PP,PERIN
InfoMulti","LETT
MARCHIORO","LTE,CARERI","LTE,CARERI","ING
FACCI","PP,PERIN","MATE
SBANOTTO"
3 ART2,"LETT
BORGO","LETT
BORGO","DIR/ECO,BIANCO","TIC
PIANEGONDA
InfoCom","TPSC
MARCHETTI","TIC
PIANEGONDA
InfoCom","ING MICRO
TABACCHINO","IRC
TAGLIAPIETRA","LETT
BORGO","TPSC
CUTRINO,MARCHETTI
InfoCom","LETT
BORGO","STO
BORGO","TPSC
MARCHETTI","FRA,FABBI","DIR/ECO,BIANCO","ING
TABACCHINO","MATE
COMI","TPSC,CUTRINO,MARCHETTI
InfoCom","TPSC,CUTRINO,MARCHETTI
InfoCom","DIR/ECO,BIANCO","STO
BORGO","ING
TABACCHINO","FRA,FABBI","DIR/ECO,BIANCO","MATE
COMI"
3 ART2,"LETT
BORGO","LETT
BORGO","TMA,ACOCELLA","TMA,ACOCELLA","ING MICRO
IGNAZZI","LTE,CARERI,Off MacUtensili","LTE,CARERI,Off MacUtensili","IRC
TAGLIAPIETRA","LETT
BORGO","TMA,ACOCELLA","LETT
BORGO","STO
BORGO","TEEA,BELLOTTI","LTE,CARERI,Off MacUtensili","LTE,CARERI,Off MacUtensili","ING
TABACCHINO","MATE
COMI","TMA,ACOCELLA","TMA,ACOCELLA","TEEA,BELLOTTI","STO
BORGO","ING
TABACCHINO","TEEA,BELLOTTI
Elettronica,Off Elett2","TEEA,BELLOTTI
Elettronica,Off Elett2","MATE
COMI"
3 AS,"MET OP
PELLEGRIN","MATE
SCORTEGAGNA","LETT
BERTOLOTTI","PSY
MARTINI","IGIENE
RONCAGLIA","PSY
MARTINI","PSY
MARTINI","MATE
SCORTEGAGNA","DETA
GRASSO E","STO
BERTOLOTTI","LETT
BERTOLOTTI","LETT
BERTOLOTTI","MET OP
PELLEGRIN","IGIENE
RONCAGLIA","SMS
ZATTRA
Palestra","MATE
SCORTEGAGNA","STO
BERTOLOTTI","LETT
BERTOLOTTI","IRC
TAGLIAPIETRA","DETA
GRASSO E","ING
TABACCHINO","PSY
MARTINI","PSY
MARTINI","ING MICRO
TABACCHINO","DETA
GRASSO E"
3 BMa,"MATE
SBANOTTO","ING
TABACCHINO","TTIMD
CAZZOLA,PIETRIBIASI
Elettronica","TTIMD
CAZZOLA,PIETRIBIASI
Elettronica","TMA
ZOVI
Off Mec","LTE
CICCAZZO
Off Elett1","LTE
CICCAZZO
Off Elett1","LETT
LETIZIA","TMA
ZOVI
Info45","MATE
SBANOTTO","LETT
LETIZIA","LETT
LETIZIA","TEEA
GAZZIN","TEEA
GAZZIN","ING MICRO
TABACCHINO","STO
LETIZIA","LETT
LETIZIA","TMA
ZOVI","IRC
TRABUCCO","LTE
CICCAZZO
Off Elett1","TTIMD
PIETRIBIASI
Elettronica","TEEA
ESPOSITO,GAZZIN
Elettronica,Off Elett1","ING
TABACCHINO","MATE
SBANOTTO","TMA
ZOVI
Off Mec"
3 BS,"DETA
GRASSO E","ING MICRO
LACAVA","MATE
VABLÈ","LETT
APOLLONI","PSY
PIGNATELLI","PSY
PIGNATELLI","MATE
VABLÈ","DETA
GRASSO E","LETT
APOLLONI","STO
APOLLONI","STO
APOLLONI","LETT
APOLLONI","MET OP
CONTE","MATE
VABLÈ","PSY
PIGNATELLI","LETT
APOLLONI","IRC
TAGLIAPIETRA","MET OP
CONTE","MET OP
CONTE","ING
LACAVA","ING
LACAVA","DETA
GRASSO E","PSY
PIGNATELLI","PSY
PIGNATELLI","SMS
SARTORI
Palestrona"
4 AC,"LETT
BOSSARD","STO
BOSSARD","ING
DE TOMI","FRA
STOCCHERO","SMS
SARTORI
Palestrona","DIR/ECO
EBALGINELLI","LETT
BOSSARD","TPSC
CUTRINO,MARCHETTI
InfoCom","TPSC
CUTRINO,MARCHETTI
InfoCom","MATE
DE PRETTO","LETT
BOSSARD","LETT
BOSSARD","FRA
STOCCHERO","TPSC
MARCHETTI","MATE
DE PRETTO","COM
MARTINI","DIR/ECO
EBALGINELLI","ING
DE TOMI","STO
BOSSARD","IRC
TAGLIAPIETRA","COM
MARTINI","TPSC
MARCHETTI","ING MICRO
DE TOMI","MATE
DE PRETTO","DIR/ECO
EBALGINELLI"
4 AM,"STO
PAVAN","LETT
PAVAN","ING
FACCI","MATE
SCORTEGAGNA","MATE
SCORTEGAGNA","MATE
SCORTEGAGNA","TEEA
BELLOTTI
Misure","TEEA
BELLOTTI
Misure","TTIMD CICCAZZO GAZZIN
Misure","LETT
PAVAN","TTIMD
GAZZIN","ING MICRO
FACCI","TEEA
IOVANE
Elettronica","STO
PAVAN","TMA
ACOCELLA","LTE
URSO
Off Elett2","LTE
URSO
Off Elett2","TTIMD
CICCAZZO,GAZZIN
Misure","TTIMD
CICCAZZO,GAZZIN
Misure","LETT
PAVAN","TEEA
BELLOTTI","IRC
TRABUCCO","LTE
URSO
Off Elett1","LTE
URSO
Off Elett1","TMA
ACOCELLA"
4 ART,"LETT
MARCHIORO","TTIMD,ZOVI
Auto/Sald","ING MICRO
IGNAZZI","IRC
RIGHELE","MATE
CANNIZZARO","ING
LACAVA","LETT
MARCHIORO","LETT
MARCHIORO","TEEA,BELLOTTI","TEEA,BELLOTTI","LETT
MARCHIORO","STO
MARCHIORO","ING
LACAVA","MATE
CANNIZZARO","TEEA,BELLOTTI","TEEA,IOVANE,Elettronica,Misure","TEEA,IOVANE,Elettronica,Misure","SMS
SARTORI","SMS
SARTORI","TTIMD,ZOVI","STO
MARCHIORO","MATE
CANNIZZARO","TTIMD,ZOVI,Auto/Sald","TTIMD,ZOVI,Auto/Sald","TEEA,BELLOTTI"
4 ART,"LETT
MARCHIORO","TMPP
ACOCELLA
Elettronica,Misure","PP,PERIN","IRC
RIGHELE","MATE
CANNIZZARO","ING
LACAVA","LETT
MARCHIORO","LETT
MARCHIORO","LTE,BUONO","LTE,BUONO","LETT
MARCHIORO","STO
MARCHIORO","ING
LACAVA","MATE
CANNIZZARO","LTE,BUONO
CNC","PP,PERIN,CNC","PP,PERIN,CNC","SMS
SARTORI","SMS
SARTORI","TMPP
ACOCELLA","STO
MARCHIORO","MATE
CANNIZZARO","TMPP
ACOCELLA","ING MICRO
LACAVA","PP,PERIN
Auto/Sald"
4 AS,"LETT
APOLLONI","STO
APOLLONI","MATE
COMI","PSY
COPPOLA","DETA
BIANCO","IGIENE
RONCAGLIA","IGIENE
RONCAGLIA","MATE
COMI","DETA
BIANCO","SMS
ZATTRA
Palestrona","IGIENE
RONCAGLIA","IGIENE
RONCAGLIA","LETT
APOLLONI","PSY
COPPOLA","PSY
COPPOLA","SMS
ZATTRA","DETA
BIANCO","LETT
APOLLONI","PSY
COPPOLA","PSY
COPPOLA","MET OP
PELLEGRIN","MET OP
PELLEGRIN","DETA
BIANCO","MATE
COMI","LETT
APOLLONI"
4 BMa,"LETT
BERTOLOTTI","STO
BERTOLOTTI","IRC
RIGHELE","ING
TABACCHINO","MATE
DE PRETTO","TMA
ZOVI","LETT
BERTOLOTTI","TTIMD
PIETRIBIASI,URSO
Elettronica","TTIMD
PIETRIBIASI,URSO
Elettronica","TEEA ESPOSITO GAZZIN
Off Elett2","TMA
ZOVI
Info45","ING
TABACCHINO","LTE
CAZZOLA
Off Elett1","LTE
CAZZOLA
Off Elett1","TEEA
GAZZIN","LTE
CAZZOLA
Off Elett1","LTE
CAZZOLA
Off Elett1","ING MICRO
TABACCHINO","TTIMD
PIETRIBIASI","MATE
DE PRETTO","TEEA
GAZZIN","TTIMD
PIETRIBIASI","LETT
BERTOLOTTI","LETT
BERTOLOTTI","TEEA
ESPOSITO
Off Elett2"
4 BS,"STO
LETIZIA","IRC
RIGHELE","IGIENE
RONCAGLIA","DETA
BIANCO","PSY
COPPOLA","MET OP
MISTRORIGO","MET OP
MISTRORIGO","MATE
VABLÈ","IGIENE
RONCAGLIA","IGIENE
RONCAGLIA","DETA
BIANCO","PSY
COPPOLA","IGIENE
RONCAGLIA","LETT
LETIZIA","LETT
LETIZIA","DETA
BIANCO","MATE
VABLÈ","PSY
COPPOLA","LETT
LETIZIA","STO
LETIZIA","SMS
ZATTRA
Palestrona","SMS
ZATTRA
Palestrona","MATE
VABLÈ","PSY
COPPOLA","DETA
BIANCO"
5 AC,"ING MICRO
DE TOMI","IRC
TAGLIAPIETRA","COM
MARTINI","MATE
DE PRETTO","FRA
FABBI","LETT
MANTESE","LETT
MANTESE","MATE
DE PRETTO","TPSC
CASONATO","TPSC
CASONATO","FRA
FABBI","DIR/ECO
EBALGINELLI","TPSC
CASONATO","ING
DE TOMI","COM
MARTINI","DIR/ECO
EBALGINELLI","STO
MANTESE","STO
MANTESE","MATE
DE PRETTO","TPSC
CASONATO","DIR/ECO
EBALGINELLI","FRA
FABBI","SMS
ZATTRA
Palestrona","SMS
ZATTRA
Palestrona","TPSC CASONATO CUTRINO
InfoCom"
5 ART1,"TTIMD,MANIA
Auto/Sald","ING
FACCI","MATE
DE PRETTO","STO
LO BRUTTO","STO
LO BRUTTO","ING MICRO
FACCI","TEEA,IOVANE","TEEA,IOVANE","MATE
DE PRETTO","LETT
LO BRUTTO","TTIMD,MANIA,Auto/Sald","TTIMD,MANIA,Auto/Sald","MATE
DE PRETTO","STO
LO BRUTTO","LETT
LO BRUTTO","TTIMD,MANIA","TTIMD,MANIA","IRC
TRABUCCO","ING
FACCI","TMA
ZARANTONELLO
Info45","TEEA,IOVANE","TEEA,IOVANE","MATE
DE PRETTO","LETT
LO BRUTTO","TEEA
IOVANE,ZANROSSO
Elettronica,Misure"
5 ART1,"LTE,BUONO","ING
FACCI","MATE
DE PRETTO","STO
LO BRUTTO","STO
LO BRUTTO","PP
ZARANTONELLO
CNC","LTE,BUONO
CNC","ING MICRO
FACCI","MATE
DE PRETTO","LETT
LO BRUTTO","LTE,BUONO","LTE,BUONO","MATE
DE PRETTO","STO
LO BRUTTO","LETT
LO BRUTTO","PP
ZARANTONELLO
InfoMulti","PP
ZARANTONELLO","IRC
TRABUCCO","ING
FACCI","LTE,BUONO
CNC","PP,ZARANTONELLO,InfoMulti","PP,ZARANTONELLO,InfoMulti","MATE
DE PRETTO","LETT
LO BRUTTO","LTE,BUONO
CNC"
5 ART2,"MATE
SCORTEGAGNA","LTE,URSO,Off Elett2","LTE,URSO,Off Elett2","LTE,URSO,Off Elett2","TEEA
GAZZIN,IOVANE
Off Elett2","TTIMD
PIETRIBIASI","MATE
SCORTEGAGNA","LETT
LO BRUTTO","LETT
LO BRUTTO","TTIMD
IOVANE,PIETRIBIASI
Elettronica,Misure","LTE,URSO,Off Elett2","LTE,URSO,Off Elett2","LETT
LO BRUTTO","TTIMD
IOVANE,PIETRIBIASI
Misure","TTIMD
IOVANE,PIETRIBIASI
Elettronica,Misure","TMA,ZOVI
Off Mec","MATE
SCORTEGAGNA","STO
LO BRUTTO","LETT
LO BRUTTO","TEEA
GAZZIN,IOVANE
Elettronica,Off Elett2","TMA,ZOVI,Off MacUtensili","TMA,ZOVI,Off MacUtensili","TEEA,GAZZIN","IRC
TRABUCCO","TTIMD
PIETRIBIASI"
5 ART2,"MATE
SCORTEGAGNA","PP,PERIN","LTE,BUSIN,CNC","LTE,BUSIN,CNC","TMPP,ESPOSITO
Info45","PP,PERIN
InfoMulti","MATE
SCORTEGAGNA","LETT
LO BRUTTO","LETT
LO BRUTTO","LTE,BUSIN,CNC","LTE,BUSIN,CNC","LTE,BUSIN,CNC","LETT
LO BRUTTO","ING MICRO
IGNAZZI","PP,PERIN
Auto/Sald","LTE,BUSIN","MATE
SCORTEGAGNA","STO
LO BRUTTO","LETT
LO BRUTTO","TMPP,ESPOSITO
Misure","PP,PERIN,CNC","PP,PERIN,CNC","TMPP,ESPOSITO
Misure","IRC
TRABUCCO","LTE,BUSIN"
5 AS,"ING
LACAVA","MATE
CANNIZZARO","DETA
GRASSO E","IRC
TAGLIAPIETRA","LETT
BORGO","LETT
BORGO","DETA
GRASSO E","STO
BORGO","MATE
CANNIZZARO","PSY
PIGNATELLI","MET OP
CONTE","MET OP
CONTE","SMS
SARTORI
Palestra.","SMS
SARTORI
Palestra.","LETT
BORGO","ING
LACAVA","MATE
CANNIZZARO","PSY
PIGNATELLI","DETA
GRASSO E","IGIENE
RONCAGLIA","PSY
PIGNATELLI","PSY
PIGNATELLI","IGIENE
RONCAGLIA","IGIENE
RONCAGLIA","ING MICRO
LACAVA"
5 BC,"DIR/ECO
EBALGINELLI","STO
LETIZIA","LETT
LETIZIA","ING MICRO
DE TOMI","FRA
STOCCHERO","TPSC
MARANGON","TPSC
MARANGON","DIR/ECO
EBALGINELLI","IRC
TAGLIAPIETRA","LETT
LETIZIA","DIR/ECO
EBALGINELLI","FRA
STOCCHERO","SMS
ZATTRA
Palestra","SMS
ZATTRA
Palestra","TPSC CUTRINO MARANGON
InfoCom","ING
DE TOMI","COM
PIGNATELLI","STO
LETIZIA","TPSC
MARANGON","TPSC
MARANGON","FRA
STOCCHERO","FRA
STOCCHERO","LETT
LETIZIA","LETT
LETIZIA","COM
PIGNATELLI"
5 BS,"IGIENE
RONCAGLIA","IGIENE
RONCAGLIA","MET OP
CONTE","MET OP
CONTE","ING
LACAVA","STO
BERTOLOTTI","ING
LACAVA","PSY
MARTINI","PSY
MARTINI","DETA
GRASSO E","DETA
GRASSO E","ING MICRO
LACAVA","PSY
MARTINI","PSY
MARTINI","LETT
BERTOLOTTI","IGIENE
RONCAGLIA","IGIENE
RONCAGLIA","DETA
GRASSO E","LETT
BERTOLOTTI","STO
BERTOLOTTI","DETA
GRASSO E","LETT
BERTOLOTTI","SMS
SARTORI
Palestra","SMS
SARTORI
Palestra","PSY
MARTINI"
1ACTH,"ING
DALLE CARBONARE","MAT
SALMASO","LETT
GROTTO","LETT
GROTTO","SMS
DI VINCENZO","TPSC
MAURO","TPSC
MAURO","MAT
SALMASO",TIC RESCIGNO VILLAREALE,"SC INT
FACCIN LUPPINO","SC INT
FACCIN","ING
DALLE CARBONARE","LETT
GROTTO","LETT
GROTTO","MAT
SALMASO","TPSC
MAURO","TPSC
MAURO","MAT
SALMASO","GEO
ZAMBERLAN","TIC
RESCIGNO","LETT
GROTTO","LETT
GROTTO","ING
DALLE CARBONARE","TPSC
MAURO","TPSC
MAURO"
1AMTH,"SC INT
RANDON,VERLATO","SC INT
RANDON,VERLATO","MAT
PESSIA","ING
GNATA","TTPG
LODATO SAMUELE",TIC RESCIGNO SPAMPINATO,"MAT
PESSIA","TTPG
LODATO,SAMUELE","TTPG
LODATO,SAMUELE","ING
GNATA","SC INT
VERLATO","ING
GNATA","LETT
BRESSAN","LETT
BRESSAN","MAT
PESSIA","TIC
RESCIGNO","DIR
ARNONE","ING
GNATA","MAT
PESSIA","LETT
BRESSAN","SMS
MICELI","SMS
MICELI","LETT
BRESSAN","DIR
ARNONE","SC INT
VERLATO"
1ASTH,"RC
TRABUCCO","ING
DALLE CARBONARE","SC INT
FACCIN","MAT
DENTILLI","DIR
DI NOTO","SC UMA
APA","DIR
DI NOTO","ING
DALLE CARBONARE","MET OPE
LAGHETTO","MAT
DENTILLI","MET OPE
LAGHETTO","DIR
DI NOTO","MAT
DENTILLI","SMS
LAGHETTO","SMS
LAGHETTO","GEO
ZAMBERLAN","TIC
RESCIGNO SPAMPINATO","TIC
RESCIGNO SPAMPINATO","MAT
DENTILLI","MET OPE
LAGHETTO","SC INT
FACCIN,RANDON","SC INT
FACCIN,RANDON","MET OPE
LAGHETTO","SC UMA
APA","ING
DALLE CARBONARE"
1AYPH,"SC INT
LAZZARI","TDP
POZZA,RIGON","TDP
POZZA,RIGON","LTE
DAL SANTO","LTE
DAL SANTO","LTE
DAL SANTO","LTE
DAL SANTO","SC INT
LAZZARI RANDON","MAT
DALLA VALLE","ING
BRIAN","DIR
DI NOTO","RC
TRABUCCO","MAT
DALLA VALLE","TDP
POZZA,RIGON","TDP
POZZA,RIGON","MAT
DALLA VALLE","LTE
DAL SANTO","LTE
DAL SANTO","ING
BRIAN",TIC REVRENNA VILLAREALE,"DIR
DI NOTO","MAT
DALLA VALLE","GEO
ZAMBERLAN","SMS
FOSCARINI","SMS
FOSCARINI"
1BCTH,"DIR
ARNONE","TPSC
ZAMBON","TPSC
ZAMBON","MAT
SALMASO","SC INT
LAZZARI RANDON","SC INT
LAZZARI","TIC
PUGLIESE","TIC
PUGLIESE","SMS
MICELI","SMS
MICELI","MAT
SALMASO","TPSC
ZAMBON","TPSC
ZAMBON","DIR
ARNONE","RC
CATTELANI","MAT
SALMASO","MAT
SALMASO","TPSC
REVRENNA ZAMBON","TPSC
REVRENNA ZAMBON","GEO
ZAMBERLAN",TIC PUGLIESE VILLAREALE,"TPSC
REVRENNA ZAMBON","TPSC
REVRENNA ZAMBON","GEO
ZAMBERLAN","MAT
SALMASO"
1BSTH,"MET OPE
MISTRORIGO","MET OPE
MISTRORIGO","SC UMA
MINOZZO",SC UMA MINOZZO MISTRORIGO,"MAT
PESSIA","FRA
FABBI","TIC
RESCIGNO SPAMPINATO","TIC
RESCIGNO SPAMPINATO","MET OPE
MISTRORIGO","SC UMA
MINOZZO","MET OPE
MISTRORIGO","MAT
PESSIA","SMS
DI VINCENZO","RC
TRABUCCO","DIR
DI NOTO","SC INT
FACCIN,LUPPINO","SC INT
FACCIN,LUPPINO","FRA
FABBI","LETT
SALBEGO","LETT
SALBEGO","MAT
PESSIA","GEO
ZAMBERLAN","LETT
SALBEGO","LETT
SALBEGO","SC INT
FACCIN"
1BYMH,"ING
MAISTRO","MAT
CASAROTTO","TDP
SAMUELE","TDP
SAMUELE","SC INT
VERLATO","SC INT
RANDON,VERLATO","SC INT
RANDON,VERLATO","MAT
CASAROTTO","SMS
LAGHETTO","SMS
LAGHETTO","LTE
COPPONE","LTE
COPPONE","RC
TRABUCCO","ING
MAISTRO","MAT
CASAROTTO","DIR
DI NOTO","TIC
VILLAREALE","LTE
COPPONE","LTE
COPPONE","TDP
SAMUELE","GEO
ZAMBERLAN","LTE
COPPONE","LTE
COPPONE","ING
MAISTRO","MAT
CASAROTTO"
2ACTH,"SC INT
FACCIN","SC INT
FACCIN","ING
DALLE CARBONARE","TIC
LUPO","DIR
VISCOMI","TPSC
GUERRA","TPSC
GUERRA REVRENNA","TPSC
GUERRA REVRENNA","MAT
DENTILLI","RC
TRABUCCO","TIC
LUPO SPAMPINATO","MAT
DENTILLI","DIR
VISCOMI","ING
DALLE CARBONARE","ING
DALLE CARBONARE","TPSC
GUERRA REVRENNA","TPSC
GUERRA REVRENNA","SMS
DI VINCENZO","SMS
DI VINCENZO","MAT
DENTILLI","MAT
DENTILLI","ING
DALLE CARBONARE","TPSC
GUERRA","TPSC
GUERRA","DIR
VISCOMI"
2AMTH,"LETT
GROTTO","LETT
GROTTO","LTE
LODATO","LTE
LODATO","MAT
DENTILLI","LTE
LODATO","LTE
LODATO","MAT
DENTILLI","SC INT
RANDON,VERLATO","SC INT
RANDON,VERLATO","LETT
GROTTO","LETT
GROTTO","TTPG
GRISOLIA","MAT
DENTILLI","RC
TRABUCCO","SMS
LAGHETTO","SMS
LAGHETTO","DIR
FUSCO","ING
DALLE CARBONARE","ING
DALLE CARBONARE","LTE
LODATO","MAT
DENTILLI","TIC
VILLAREALE","ING
DALLE CARBONARE","TTPG
GRISOLIA"
2ASTH,"LETT
BRESSAN","DIR
VISCOMI","RC
CATTELANI","MAT
CASAROTTO","SC UMA
MINOZZO","MAT
CASAROTTO","MAT
CASAROTTO","SMS
DI VINCENZO","LETT
BRESSAN","LETT
BRESSAN","MAT
CASAROTTO","SC UMA
MINOZZO MISTRORIGO","SC UMA
MINOZZO MISTRORIGO","TIC
LUPO SPAMPINATO","TIC
LUPO SPAMPINATO","MET OPE
MISTRORIGO","LETT
BRESSAN","LETT
BRESSAN","SC INT
FACCIN RANDON","SC INT
FACCIN","LETT
BRESSAN","LETT
BRESSAN","MAT
CASAROTTO","DIR
VISCOMI","MET OPE
MISTRORIGO"
2AYPH,"LETT
SALBEGO","SC INT
LAZZARI","DIR
VISCOMI","TDP
POZZA,SORBELLO","TDP
POZZA,SORBELLO",TDP POZZA SORBELLO,"SC INT
LAZZARI LUPPINO","LTE
DAL SANTO","LTE
DAL SANTO","TIC
VILLAREALE","LTE
DAL SANTO","LTE
DAL SANTO","ING
GNATA","MAT
PESSIA","LETT
SALBEGO","ING
GNATA","DIR
VISCOMI","MAT
PESSIA","LTE
DAL SANTO","LTE
DAL SANTO","LETT
SALBEGO","LETT
SALBEGO",TDP POZZA SORBELLO,"SMS
LAGHETTO","SMS
LAGHETTO"
2BCTH,TPSC REVRENNA ZAMBON,"TIC
LUPO","ING
GASPARELLA","ING
GASPARELLA","SMS
MICELI","TPSC
ZAMBON","SMS
MICELI","MAT
DALLA VALLE","SC INT
FACCIN","DIR
VISCOMI","ING
GASPARELLA","MAT
DALLA VALLE","RC
CATTELANI","TPSC
ZAMBON","TPSC
ZAMBON","TIC
LUPO SPAMPINATO","MAT
DALLA VALLE","SC INT
FACCIN RANDON","DIR
VISCOMI","TPSC
ZAMBON","LETT
PUPIN","LETT
PUPIN","MAT
DALLA VALLE","TPSC
REVRENNA ZAMBON","TPSC
REVRENNA ZAMBON"
2BMTH,"LTE
BAVILA","LTE
BAVILA","SC INT
RANDON,VERLATO","SC INT
RANDON,VERLATO","ING
GASPARELLA","TIC
PUGLIESE","ING
GASPARELLA","ING
GASPARELLA","MAT
CASAROTTO","LETT
PISANELLO","LETT
PISANELLO","LTE
BAVILA","LTE
BAVILA","SMS
FOSCARINI","SMS
FOSCARINI","MAT
CASAROTTO","LETT
PISANELLO","LETT
PISANELLO","TTPG
SAMUELE","DIR
FUSCO","MAT
CASAROTTO",TIC PUGLIESE VILLAREALE,"LETT
PISANELLO","LTE
BAVILA","LTE
BAVILA"
2BSTH,"SMS
MICELI","SMS
MICELI","ING
MAISTRO","DIR
VISCOMI","MET OPE
LAGHETTO","SC UMA
BALESTRA","DIR
VISCOMI","SC INT
FACCIN","FRA
FABBI","MAT
DALLA VALLE","ING
MAISTRO","TIC
LUPO SPAMPINATO","TIC
LUPO SPAMPINATO","MAT
DALLA VALLE","SC UMA
BALESTRA","MET OPE
LAGHETTO","FRA
FABBI","MAT
DALLA VALLE",SC UMA BALESTRA LAGHETTO,"ING
MAISTRO","MAT
DALLA VALLE","MET OPE
LAGHETTO","SC INT
FACCIN,RANDON","SC INT
FACCIN,RANDON","SMS
MICELI"
2BYMH,"MAT
CASAROTTO","LTE
VACCA","LTE
VACCA","LETT
BRESSAN","LETT
BRESSAN","LTE
VACCA","LTE
VACCA","SC INT
LUPPINO,RIGONI","SC INT
LUPPINO,RIGONI","MAT
CASAROTTO","LETT
BRESSAN","LETT
BRESSAN","MAT
CASAROTTO","SMS
MICELI","SMS
MICELI","LETT
BRESSAN","LTE
VACCA","LTE
VACCA","DIR
FUSCO","SC INT
RIGONI","RC
CATTELANI","DIR
FUSCO","TDP
FRAU","MAT
CASAROTTO","LETT
BRESSAN"
3ACTH,"TPSC
MARTINI","TPSC
MARTINI","ING
BRIAN","RC
CATTELANI","MAT
SALMASO","COM
COPPOLA","COM
COPPOLA",TPSC MARTINI VILLAREALE,"DIR
FUSCO","DIR
FUSCO","TPSC
MARTINI VILLAREALE","TPSC
MARTINI VILLAREALE","MAT
SALMASO","ING
BRIAN","TPSC
MARTINI","ING
BRIAN","DIR
FUSCO","TPSC
MARTINI","MAT
SALMASO","MAT
SALMASO","DIR
FUSCO","SMS
LAGHETTO","SMS
LAGHETTO","TPSC
MARTINI","TPSC
MARTINI"
3AMTH,"MAT
RIGHELE","ING
MAISTRO","SMS
MICELI","SMS
MICELI","TEEA
GRISOLIA","TMA
FACCIN","MAT
RIGHELE","RC
TRABUCCO","TIMD
FRAU","TIMD
FRAU","TMA
FACCIN","TMA
FACCIN","ING
MAISTRO","TEEA
BAVILA GRISOLIA","TIMD
FRAU","TIMD
FRAU","TIMD
FRAU","MAT
RIGHELE","TMA
FACCIN","TMA
FACCIN","TEEA
BAVILA,GRISOLIA","TEEA
BAVILA,GRISOLIA","LETT
PUPIN","LETT
PUPIN","ING
MAISTRO"
3ARTH,"MAT
PESSIA","RC
CATTELANI","TPSC,GUERRA","TPSC,GUERRA","INFO,LUPO","DIR,FUSCO","LETT
GROTTO","LETT
GROTTO","TPSC,GUERRA","TPSC,GUERRA","MAT
PESSIA","ING
BRIAN","DIR,FUSCO","DIR,FUSCO","TPSC
GUERRA,VILLAREALE","LETT
GROTTO","LETT
GROTTO","TPSC
GUERRA,VILLAREALE","TPSC
GUERRA,VILLAREALE","ING
BRIAN","SMS
DI VINCENZO","SMS
DI VINCENZO","ING,BRIAN","LETT
GROTTO","LETT
GROTTO"
3ARTH,"MAT
PESSIA","RC
CATTELANI","PSI,BALESTRA","PSI,BALESTRA","MET OPE
MISTRORIGO","ING
GASPARELLA","LETT
GROTTO","LETT
GROTTO","DIR,ARNONE","FRA,FABBI","MAT
PESSIA","ING
BRIAN","PSI,BALESTRA","PSI,BALESTRA","MET OPE
MISTRORIGO","LETT
GROTTO","LETT
GROTTO","PSI
BALESTRA","FRA,FABBI","ING
BRIAN","SMS
DI VINCENZO","SMS
DI VINCENZO","MET OPE
MISTRORIGO","LETT
GROTTO","LETT
GROTTO"
3ASTH,"MET OPE
LAGHETTO","PSI
APA","PSI
APA","MAT
PESSIA","ING
DALLE CARBONARE","MAT
PESSIA","FRA
FABBI","DIR
ARNONE","SMS
DI VINCENZO","SMS
DI VINCENZO","PSI
APA","PSI
APA","ING
DALLE CARBONARE","RC
CATTELANI","DIR
ARNONE","FRA
FABBI","MET OPE
LAGHETTO","PSI
APA","DIR
ARNONE","MAT
PESSIA","ING
DALLE CARBONARE","MAT
PESSIA","MAT
PESSIA","MET OPE
LAGHETTO","SMS
DI VINCENZO"
3AYPH,"SMS
LAGHETTO","SMS
LAGHETTO","MAT
SALMASO","LTE
RIGON","LTE
RIGON","ING
MAISTRO","PP
POZZA,SORBELLO","PP
POZZA,SORBELLO","RC
TRABUCCO","MAT
SALMASO","TMP
SORBELLO","TMP
SORBELLO","LTE
RIGON","MAT
SALMASO","ING
MAISTRO","LTE
RIGON","LTE
RIGON","PP
POZZA,SORBELLO","PP
POZZA,SORBELLO","TMP
SORBELLO","ARTE
SORBELLO","PP
POZZA SORBELLO","ING
MAISTRO","LTE
RIGON","LTE
RIGON"
3BMTH,"TMA
FRAU","TMA
FRAU","TIMD
FACCIN","LTE
VACCA","LTE
VACCA","RC
TRABUCCO","TIMD
COPPONE FACCIN","LTE
VACCA","TEEA
BERTACCHE","TEEA
BERTACCHE","TMA
FRAU","TMA
FRAU",TEEA BERTACCHE LODATO,"LTE
VACCA","LTE
VACCA","LTE
VACCA","TIMD
FACCIN","TIMD
FACCIN","TEEA
BERTACCHE LODATO","TEEA
BERTACCHE LODATO","TIMD
COPPONE FACCIN","SMS
FOSCARINI","SMS
FOSCARINI","TMA
FRAU","TMA
FRAU"
4ACTH,"DIR
VISCOMI","LETT
SALBEGO","LETT
SALBEGO","TPSC
MARTINI","TPSC
MARTINI","TPSC
MARTINI","TPSC
MARTINI","ING
MAISTRO","LETT
SALBEGO","LETT
SALBEGO","SMS
LAGHETTO","SMS
LAGHETTO",TPSC MARTINI VILLAREALE,"LETT
SALBEGO","MAT
DENTILLI","LETT
SALBEGO","LETT
SALBEGO","MAT
DENTILLI","TPSC
MARTINI","DIR
VISCOMI","ING
MAISTRO","TPSC
MARTINI","TPSC
MARTINI","MAT
DENTILLI","COM
BALESTRA"
4AMTH,"TEEA
GRISOLIA","LETT
DAL FERRO","LETT
DAL FERRO","LTE
CICCAZZO","LTE
CICCAZZO","MAT
RIGHELE","ING
DALLE CARBONARE","TIMD
BAVILA ZANROSSO","TIMD
BAVILA ZANROSSO","TEEA
GRISOLIA LODATO","ING
DALLE CARBONARE","TMA
SAMUELE,VACCA","TMA
SAMUELE,VACCA","LETT
DAL FERRO","LETT
DAL FERRO",TIMD BAVILA ZANROSSO,"RC
CATTELANI","TEEA
GRISOLIA LODATO","SMS
MICELI","SMS
MICELI","TIMD
ZANROSSO","LTE
CICCAZZO","LTE
CICCAZZO","TMA
SAMUELE","TMA
SAMUELE"
4ASTH,"ING
BRIAN","MET OPE
LAGHETTO","LETT
PISANELLO","PSI
APA","PSI
APA","LETT
PISANELLO","LETT
PISANELLO","DIR
VISCOMI","ING
BRIAN","MET OPE
LAGHETTO","ING
BRIAN","RC
CATTELANI","PSI
APA","DIR
VISCOMI","DIR
VISCOMI","PSI
APA","PSI
APA","MET OPE
LAGHETTO","LETT
PISANELLO","LETT
PISANELLO","DIR
VISCOMI","DIR
VISCOMI","SMS
DI VINCENZO","SMS
DI VINCENZO","LETT
PISANELLO"
4AYPH,"MAT
SALMASO","LTE
DAL SANTO","LTE
DAL SANTO","LETT
PISANELLO","ING
GNATA","SMS
LAGHETTO","SMS
LAGHETTO","LETT
PISANELLO","TDM
MAURO","PP
POZZA RIGON","RC
TRABUCCO","MAT
SALMASO",ARTE POZZA SORBELLO,"LTE
DAL SANTO","LTE
DAL SANTO","LETT
PISANELLO","ING
GNATA","TMP
RIGON","TMP
RIGON","PP
POZZA RIGON","LETT
PISANELLO","LETT
PISANELLO","TDM
MAURO",ARTE POZZA SORBELLO,"LTE
DAL SANTO"
4BMTH,"TMA
COPPONE SAMUELE","TMA
COPPONE SAMUELE","TIMD
BAVILA","TEEA
GRISOLIA","RC
CATTELANI","TIMD
BAVILA BERTACCHE","TIMD
BAVILA BERTACCHE","TEEA
GRISOLIA","TEEA
GRISOLIA","TMA
SAMUELE","TIMD
BERTACCHE","LTE
CICCAZZO","LTE
CICCAZZO","TMA
COPPONE SAMUELE","TMA
COPPONE SAMUELE","SMS
MICELI","SMS
MICELI","RC
CATTELANI","TEEA
GRISOLIA","TEEA
GRISOLIA","TMA
SAMUELE","TMA
SAMUELE","TEEA
GRISOLIA","LTE
CICCAZZO","LTE
CICCAZZO"
5ACTH,"TPSC
MAURO VILLAREALE","TPSC
MAURO VILLAREALE","MAT
DENTILLI","LETT
DAL FERRO","DIR
FUSCO","LETT
DAL FERRO","DIR
FUSCO","DIR
FUSCO","ING
GNATA","COM
BALESTRA","ING
GNATA","LETT
DAL FERRO","LETT
DAL FERRO","TPSC
MAURO","TPSC
MAURO","DIR
FUSCO","MAT
DENTILLI","SMS
LAGHETTO","SMS
LAGHETTO","COM
BALESTRA","TPSC
MAURO","TPSC
MAURO","MAT
DENTILLI","LETT
DAL FERRO","LETT
DAL FERRO"
5ARTH,"LTE,VACCA","TEEA
CICCAZZO,GRISOLIA","TEEA
CICCAZZO,GRISOLIA","TMA,FACCIN","MAT
RIGHELE","TIMD,ZANROSSO","TIMD,ZANROSSO","MAT
RIGHELE","LTE,VACCA","LTE,VACCA","RC
CATTELANI","ING
MAISTRO","TMA,FACCIN","TMA,FACCIN","TEEA
CICCAZZO,GRISOLIA","TMA,FACCIN","TIMD
BAVILA,ZANROSSO","TIMD
BAVILA,ZANROSSO","ING
MAISTRO","MAT
RIGHELE","LTE,VACCA","ING
MAISTRO","TIMD
BAVILA,ZANROSSO","SMS
MICELI","LETT
PUPIN"
5ARTH,"TMP,FACCIN,LODATO","TMP,FACCIN,LODATO","LTE,COPPONE","LTE,COPPONE","MAT
RIGHELE","PP,FRAU","PP,FRAU","MAT
RIGHELE","LTE,COPPONE","LTE,COPPONE","RC
CATTELANI","ING
MAISTRO","PP,FRAU","PP,FRAU","TMP,FACCIN","LTE,COPPONE","LTE,COPPONE","PP,FRAU","ING
MAISTRO","MAT
RIGHELE","PP,FRAU","ING
MAISTRO","TMP
FACCIN,LODATO","SMS
MICELI","LETT
PUPIN"
5ASTH,"RC
CATTELANI","ING
BRIAN","MET OPE
LAGHETTO","MET OPE
LAGHETTO","PSI
BALESTRA","DIR
ARNONE","DIR
ARNONE","PSI
BALESTRA","PSI
BALESTRA","MAT
SCALISI","SMS
DI VINCENZO","SMS
DI VINCENZO","MET OPE
LAGHETTO","MAT
SCALISI","ING
BRIAN","PSI
BALESTRA","PSI
BALESTRA","DIR
ARNONE","MAT
SCALISI","MAT
SCALISI","ING
BRIAN","DIR
ARNONE","PSI
BALESTRA","PSI
BALESTRA","MET OPE
LAGHETTO"
5BSTH,"PSI
APA","DIR
ARNONE","DIR
ARNONE","ING
BRIAN","ING
BRIAN","SMS
DI VINCENZO","SMS
DI VINCENZO","PSI
APA","PSI
APA","MET OPE
MISTRORIGO","DIR
ARNONE","DIR
ARNONE","ING
BRIAN","SMS
DI VINCENZO","SMS
DI VINCENZO","RC
CATTELANI","MET OPE
MISTRORIGO","MET OPE
MISTRORIGO","PSI
APA","PSI
APA","DIR
ARNONE","ING
BRIAN","RC
CATTELANI","MET OPE
MISTRORIGO","PSI
APA"`;
